- server/sonar-server/src/main/java/org/sonar/server/user/index/UserIndex.java
Improve performance of ES request on users
Searching for users by SCM account does not require scoring, so filters must be used instead of queries.
> Improve performance of ES request on users

- server/sonar-server/src/main/java/org/sonar/server/computation/issue/IssueComputation.java
- server/sonar-server/src/test/java/org/sonar/server/computation/issue/IssueComputationTest.java
Keep compatibility with issue-assign and cockpit plugins
Do not override author and assignee fields of new issues
> Keep compatibility with issue-assign and cockpit plugins

- server/sonar-server/src/main/java/org/sonar/server/issue/index/IssueIndex.java
- server/sonar-server/src/main/java/org/sonar/server/issue/ws/SearchAction.java
- server/sonar-server/src/test/java/org/sonar/server/issue/index/IssueIndexTest.java
Up to 4.5.x, ``createdAfter``/``createdBefore`` used strict comparison, excluding the bounds. When we migrated to ES in 5.0, those filters became inclusive, which poses an issue with differential periods. The first commit of this PR reverts to exclusive behavior.
The second commit avoids 500 error when ``createdAfter == createdBefore`` (there is a check that createdAfter.before(createdBefore) to avoid issues with the date histogram aggregation on creation date).
> Fix issue date filters

- server/sonar-server/src/main/java/org/sonar/server/rule/ws/RuleMapping.java
- server/sonar-server/src/test/java/org/sonar/server/rule/ws/RulesWebServiceMediumTest.java
- server/sonar-server/src/test/resources/org/sonar/server/rule/ws/RulesWebServiceMediumTest/search_2_rules_fields.json
The issue here was that a simple ``Mapper`` does not declare which document fields the WS field maps to, whereas an ``IndexMapper`` allows this.
> SONAR-5885 Fix mapping of htmlDesc attribute to fetch correct fields in ES

- server/sonar-server/src/main/java/org/sonar/server/qualityprofile/QProfileReset.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/QProfileResetMediumTest.java
SONAR-6011 Restoring built-in profiles does not update existing rule parameters
> SONAR-6011 Restoring built-in profiles does not update existing rule parameters

- server/sonar-web/Gruntfile.coffee
- server/sonar-web/package.json
The longest step in `grunt build` is `uglify`. I replaced it by `uglify_parallel` that runs tasks in parallel.
Also I enabled `jit-grunt` that enables lazy loading of grunt plugins.
On my machine I get 100% boost (7s vs 14s).
> speed up uglify js step

- server/sonar-server/src/main/java/org/sonar/server/rule/RubyRuleService.java
- server/sonar-server/src/test/java/org/sonar/server/rule/RubyRuleServiceTest.java
Add search the ability to search for rules by profiles in RubyRuleService
Needed to fix SQALE-269
> Add the ability to search for rules by profiles in RubyRuleService - Needed to fix SQALE-269

- server/sonar-server/src/main/java/org/sonar/server/rule/RegisterRules.java
- server/sonar-server/src/test/java/org/sonar/server/rule/RegisterRulesMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/rule/RegisterRulesTest.java
SONAR-6238 Updating only the name of a rule is not taking in account when synchronizing rules at startup
> SONAR-6238 Updating only the name of a rule is not taking in account when synchronizing rules at startup

- plugins/sonar-core-plugin/src/main/resources/org/sonar/plugins/core/widgets/custom_measures.html.erb
- server/sonar-web/src/main/webapp/WEB-INF/app/models/project_measure.rb
SONAR-6206 Manual Measures of type String are not displayed in the Custom Measure widget
> SONAR-6206 Manual Measures of type String are not displayed in the Custom Measure widget

- server/sonar-server/src/main/java/org/sonar/server/platform/DefaultServerFileSystem.java
- server/sonar-server/src/main/java/org/sonar/server/platform/TempFolderProvider.java
- server/sonar-server/src/test/java/org/sonar/server/platform/TempFolderProviderTest.java
SONAR-6348 Property sonar.path.temp is ignored by Ruby on Rails application
> SONAR-6348 Property sonar.path.temp is ignored by Ruby on Rails application

- server/sonar-server/src/main/java/org/sonar/server/util/CloseableIterator.java
- server/sonar-server/src/test/java/org/sonar/server/util/CloseableIteratorTest.java
Hasnext() should not call doNext() when iterator already closed
> Hasnext() should not call doNext() when iterator already closed

- server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/InstalledPluginsWsAction.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginsWs.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginsWsAction.java
- server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-installed_plugins.json
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/InstalledPluginsWsActionTest.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginsWsTest.java
provides the same data as RoR WS /api/updatecenter/installed_plugins but only in JSON format
another PR will make the new WS return more info about each plugin
> SONAR-6376 add Java Ws /api/plugins/installed

- sonar-application/src/main/assembly/conf/wrapper.conf
See https://jira.codehaus.org/browse/SONAR-6445. Decreasing to 8Mb is now possible with Java 7.
> SONAR-6445 Decrease the max memory used by server bootstrapper process

- server/sonar-server/src/main/java/org/sonar/server/db/migrations/PlatformDatabaseMigrationExecutorServiceImpl.java
small follow-up PR for SONAR-6366
threads should be named, especially long living one, thread name can be very helpful with reading a thread dump
> SONAR-6366 threads should be named

- server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/CancelAllPluginsWsAction.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/CancelAllPluginsWsActionTest.java
adds new WS in Java to cancel all updates/installs of plugins (ie. download) and uninstalls
new WS is bound to URL /api/plugins/cancel_all
> SONAR-6384 add java WS to cancel all plugins install/update/uninstall

- server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginUpdateAggregator.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginWSCommons.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ws/UpdatesPluginsWsAction.java
- server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-updates_plugins.json
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/AbstractUpdateCenterBasedPluginsWsActionTest.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/AvailablePluginsWsActionTest.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginUpdateAggregateBuilderTest.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginUpdateAggregatorTest.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/ws/UpdatesPluginsWsActionTest.java
this PR modifies the WS code to aggregate PluginUpdate objects from UpdateCenter so that the WS sends out information in the target format (multiple release per plugin object instead of one plugin for each release)
also, it modifies the unit test to test the sample response instead of some other json response specific to the unit test
> SONAR-6379 fix response to display many updates per plugin

- server/sonar-server/src/main/java/org/sonar/server/platform/Platform.java
- server/sonar-server/src/test/java/org/sonar/server/activity/ws/ActivitiesWsMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/ws/HistoryActionMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/IssueBulkChangeServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/IssueCommentServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/IssueServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/ws/SearchActionComponentsMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/ws/SearchActionMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/permission/InternalPermissionServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/platform/ServerTesterPlatform.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/QProfileExportersTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/QProfileServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/RegisterQualityProfilesMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/CompareActionMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/CreateActionMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/tester/ServerTester.java
- server/sonar-server/src/test/java/org/sonar/server/view/index/ViewIndexerMediumTest.java
this PR introduces a small (10s faster build on my box) optimization to ServerTester by not launching level5 (ie. startup tasks) by default
unit tests using `ServerTester` must now call `withStartupTasks()` method to trigger startyp tasks when `ServerTester` is created
> ServerTester don't do startup tasks by default anymore

- server/sonar-server/src/main/java/org/sonar/server/es/BaseIndexer.java
- server/sonar-server/src/main/java/org/sonar/server/es/IndexDefinitions.java
- server/sonar-server/src/main/java/org/sonar/server/search/IndexSynchronizer.java
- server/sonar-server/src/test/java/org/sonar/server/activity/ws/ActivitiesWsMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/ws/HistoryActionMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/es/EsTester.java
- server/sonar-server/src/test/java/org/sonar/server/es/IndexCreatorTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/IssueBulkChangeServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/IssueCommentServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/IssueServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/ws/SearchActionComponentsMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/ws/SearchActionMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/permission/InternalPermissionServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/QProfileServiceMediumTest.java
- server/sonar-server/src/test/java/org/sonar/server/tester/ServerTester.java
now, to use `ServerTester` with ES indexes, one must call `ServerTester.withEsIndexes()`, only few medium test actually require ES indexes
> do not create ES indexes for every ServerTester instances

- server/sonar-server/src/main/java/org/sonar/server/component/ComponentCleanerService.java
- sonar-db/src/main/java/org/sonar/db/MyBatis.java
- sonar-db/src/main/java/org/sonar/db/purge/PurgeDao.java
- sonar-db/src/main/java/org/sonar/db/purge/PurgeMapper.java
- sonar-db/src/main/resources/org/sonar/db/purge/PurgeMapper.xml
- sonar-db/src/test/java/org/sonar/db/purge/PurgeDaoTest.java
Simplify deletion of a project in PurgeDao
- Rename deleteResourceTree to deleteProject
- deleteProject only takes a uuid as paramter (instead of a IdUUidPair)
> Simplify deletion of a project in PurgeDao

- server/sonar-server/src/main/java/org/sonar/server/computation/component/PathAwareVisitorWrapper.java
- server/sonar-server/src/main/java/org/sonar/server/computation/component/TypeAwareVisitorWrapper.java
- server/sonar-server/src/main/java/org/sonar/server/computation/component/VisitorWrapper.java
- server/sonar-server/src/main/java/org/sonar/server/computation/component/VisitorsCrawler.java
- server/sonar-server/src/main/java/org/sonar/server/computation/step/ExecuteVisitorsStep.java
- server/sonar-server/src/test/java/org/sonar/server/computation/component/ReportComponent.java
- sonar-core/src/main/java/org/sonar/core/util/logs/DefaultProfiler.java
- sonar-core/src/main/java/org/sonar/core/util/logs/NullProfiler.java
- sonar-core/src/main/java/org/sonar/core/util/logs/Profiler.java
- sonar-core/src/test/java/org/sonar/core/util/logs/DefaultProfilerTest.java
this PR contains:
* improvements on the sonar.util Profiler implementation (less String creation when actual log level is lower than the configured one)
* ReportComponent now create Component implementations for tests which always have a key
** this can be changed now because Component implementation of production code is now immutable (see @julienlancelot 's PR)
* the cumulative execution time of each visitor is now displayed in logs at INFO level
* bonus: at TRACE level, the Component Visitor execution time for each component will be displayed
> Compute Engine logs of execution duration of each component visitor

- server/sonar-server/src/main/java/org/sonar/server/platform/ws/DbMigrationJsonWriter.java
- server/sonar-server/src/main/java/org/sonar/server/platform/ws/DbMigrationStatusAction.java
- server/sonar-server/src/main/java/org/sonar/server/platform/ws/MigrateDbAction.java
- server/sonar-server/src/test/java/org/sonar/server/platform/ws/DbMigrationStatusActionTest.java
- server/sonar-server/src/test/java/org/sonar/server/platform/ws/MigrateDbActionTest.java
fix for 5.2 of WS response of DB migration related WebService when the DB can not be reached
not error message is related to the problem and explicit
> SONAR-6652 explicit error when DB is disconnected in WS response

- server/sonar-server/src/main/java/org/sonar/server/computation/source/DuplicationLineReader.java
- server/sonar-server/src/main/java/org/sonar/server/computation/source/HighlightingLineReader.java
- server/sonar-server/src/main/java/org/sonar/server/computation/source/RangeOffsetConverter.java
- server/sonar-server/src/main/java/org/sonar/server/computation/source/SymbolsLineReader.java
- server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistFileSourcesStep.java
- server/sonar-server/src/test/java/org/sonar/server/computation/source/HighlightingLineReaderTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/source/RangeOffsetConverterTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/source/SymbolsLineReaderTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistFileSourcesStepTest.java
- sonar-plugin-api/src/main/java/org/sonar/api/utils/log/BaseLogger.java
- sonar-plugin-api/src/main/java/org/sonar/api/utils/log/Logger.java
- sonar-plugin-api/src/test/java/org/sonar/api/utils/log/ConsoleLoggerTest.java
When a source is badly encoded, the Compute Engine will no more fail but will ignore remaining highlighting / symbols and will display a warning log.
> SONAR-6318 Not fail on bad encoding in ComputeEngine

- server/sonar-server/src/main/java/org/sonar/server/computation/monitoring/CEQueueStatus.java
- server/sonar-server/src/main/java/org/sonar/server/computation/monitoring/CEQueueStatusImpl.java
- server/sonar-server/src/test/java/org/sonar/server/computation/monitoring/CEQueueStatusImplConcurrentTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/monitoring/CEQueueStatusImplTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/queue/CeQueueImplTest.java
and they should not required the CEQueueStatusImpl object to be initialized either
this way, monitoring can query the metrics of CEQueueStatus through JMX even before the object is initialized
> SONAR-6995 CEQueueStatus get method should not modify state

- server/sonar-server/src/main/java/org/sonar/server/user/UserUpdater.java
- server/sonar-server/src/test/java/org/sonar/server/user/UserUpdaterTest.java
- server/sonar-server/src/test/resources/org/sonar/server/user/UserUpdaterTest/update_technical_user.xml
SONAR-7036 Update password of technical user
When using an external authentication (like LDAP), it's now possible possible to update the password of technical accounts
> SONAR-7036 Update password of technical user

- server/sonar-web/src/main/js/apps/overview/components/issue-measure.js
HI guys.
I found these two non-localizable strings in the SonarQube UI. It's a trivial change.
> Replace hardcoded string in AddedRemovedDebt component

- server/sonar-server/src/main/java/org/sonar/server/computation/monitoring/CEQueueStatus.java
- server/sonar-server/src/main/java/org/sonar/server/computation/monitoring/CEQueueStatusImpl.java
- server/sonar-server/src/main/java/org/sonar/server/computation/queue/CeQueue.java
- server/sonar-server/src/main/java/org/sonar/server/computation/queue/CeQueueImpl.java
- server/sonar-server/src/test/java/org/sonar/server/computation/monitoring/CEQueueStatusImplTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/monitoring/ComputeEngineQueueMonitorTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/queue/CeQueueImplTest.java
allow possibility to batch insert tasks into the CeQueue:
* using a single transaction for inserting all tasks
* using a single request to retrieve all components referenced by the inserted tasks rather than one per task
> SONAR-7183 faster ce submit

- it/it-tests/src/test/java/util/selenium/SeleneseTest.java
- sonar-core/pom.xml
This change dumps js logs to the screen, when assertion fails. The motivation is to quickly see if there is  a js error.
> dump js logs

- sonar-application/src/main/assembly/conf/sonar.properties
SONAR-7430 Wrong remote IP in access.log when server is behind a reverse proxy
> SONAR-7430 Wrong remote IP in access.log when server is behind a reverse proxy

- it/it-tests/src/test/java/it/test/CoverageTest.java
- it/it-tests/src/test/resources/test/CoverageTest/it_coverage-expected.json
- server/sonar-server/src/main/java/org/sonar/server/computation/source/CoverageLineReader.java
- server/sonar-server/src/test/java/org/sonar/server/computation/source/CoverageLineReaderTest.java
- sonar-scanner-engine/src/main/java/org/sonar/batch/report/CoveragePublisher.java
- sonar-scanner-engine/src/test/java/org/sonar/batch/report/CoveragePublisherTest.java
- sonar-scanner-protocol/src/main/protobuf/scanner_report.proto
It is required to distinguish unset from 0 for ut hits and it hits.
> SONAR-7497 Fix change of behavior for coverage after move to proto3

- sonar-ws/src/main/java/org/sonarqube/ws/client/HttpConnector.java
- sonar-ws/src/test/java/org/sonarqube/ws/client/HttpConnectorTest.java
since we didn't set it for Java 8, SSL connections opened with OkHttpClient under Java 8 didn't have any of the SSL parameters
> SONAR-7498 OkHttpClient doesn't use ssl socket factory by default

- sonar-plugin-api/src/main/java/org/sonar/api/utils/Duration.java
- sonar-plugin-api/src/test/java/org/sonar/api/utils/DurationTest.java
This PR allow to set 0min the gap multiplier or the offset of a remediation function
> SONAR-7570 A duration of 0 minute should be converted to "0min" instead of empty

- it/it-tests/src/test/java/it/issue/IssuePurgeTest.java
- server/sonar-server/src/main/java/org/sonar/server/component/ComponentCleanerService.java
- server/sonar-server/src/main/java/org/sonar/server/computation/dbcleaner/IndexPurgeListener.java
- server/sonar-server/src/main/java/org/sonar/server/computation/dbcleaner/ProjectCleaner.java
- server/sonar-server/src/main/java/org/sonar/server/issue/index/IssueIndex.java
- server/sonar-server/src/main/java/org/sonar/server/issue/index/IssueIndexer.java
- server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/BulkRuleActivationActions.java
- server/sonar-server/src/test/java/org/sonar/server/computation/dbcleaner/IndexPurgeListenerTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/dbcleaner/ProjectCleanerTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/index/IssueIndexTest.java
- server/sonar-server/src/test/java/org/sonar/server/issue/index/IssueIndexerTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/QProfilesWsTest.java
- sonar-db/src/main/java/org/sonar/db/purge/PurgeDao.java
- sonar-db/src/main/java/org/sonar/db/purge/PurgeListener.java
- sonar-db/src/main/java/org/sonar/db/purge/PurgeMapper.java
- sonar-db/src/main/resources/org/sonar/db/purge/PurgeMapper.xml
- sonar-db/src/test/java/org/sonar/db/purge/PurgeDaoTest.java
SONAR-7108 Delete Issues from index when purging old issues
Purge from index was already working when property 'sonar.dbcleaner.daysBeforeDeletingClosedIssues' was not equal to 0. Now it's working whatever the value is.
> SONAR-7108 Delete Issues from index when purging old issues

- server/sonar-web/src/main/webapp/WEB-INF/app/controllers/api/properties_controller.rb
SONAR-7539 WS api/properties should return licenses if user is authenticated
> SONAR-7539 WS api/properties should return licenses if user is authenticated

- server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/JavaProcessLauncher.java
- server/sonar-process-monitor/src/test/java/org/sonar/process/monitor/JavaProcessLauncherTest.java
because the JVM's temp dir might just be read only (eg. temp dir of windows services launched with Local System Account on recent windows versions is actuallt read only)
> SONAR-7154 main process must create property file in SQ's temp dir

- README.md
The links in reference-style syntax are not visible on GitHub, and as such, not clickable either. I converted them to a "Links" section to make them visible and clickable, and added a "How to contribute" link pointing to the Development page on the main website. This should make the project more accessible to potential contributors.
> Make links clickable on GitHub

- server/sonar-server/src/main/java/org/sonar/server/computation/filemove/FileMoveDetectionStep.java
- server/sonar-server/src/main/java/org/sonar/server/computation/filemove/MatchesByScore.java
- server/sonar-server/src/main/java/org/sonar/server/computation/filemove/MutableMovedFilesRepositoryImpl.java
- server/sonar-server/src/test/java/org/sonar/server/computation/filemove/FileMoveDetectionStepTest.java
- server/sonar-server/src/test/java/org/sonar/server/computation/filemove/MatchesByScoreTest.java
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1235_add_component_uuid_to_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1236_populate_component_uuid_of_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1237_delete_orphan_duplications_index_rows_without_component.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1238_make_component_uuid_not_null_on_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1239_add_analysis_uuid_to_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1240_populate_analysis_uuid_of_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1241_delete_orphan_duplications_index_rows_without_analysis.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/1242_make_analysis_uuid_not_null_on_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/AddAnalysisUuidColumnToDuplicationsIndex.java
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/AddComponentUuidColumnToDuplicationsIndex.java
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/DeleteOrphanDuplicationsIndexRowsWithoutComponent.java
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v1/MakeComponentUuidNotNullOnDuplicationsIndex.java
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v2/1235_add_component_uuid_and_analysis_uuid_to_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v2/1236_populate_component_uuid_and_analysis_uuid_of_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v2/1237_delete_orphan_duplications_index_rows_without_component_or_analysis.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v2/1238_make_component_uuid_and_analysis_uuid_not_null_on_duplications_index.rb
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v2/AddComponentUuidAndAnalysisUuidColumnToDuplicationsIndex.java
- server/sonar-server/src/test/resources/org/sonar/server/computation/filemove/FileMoveDetectionStepTest/v2/MakeComponentUuidAndAnalysisUuidNotNullOnDuplicationsIndex.java
* Real technical bug causing the error was that matches
were not properly filtered so that a file that was already
matched could be matched again
* This also allowed to spot a functional bug: matches candidates were
processed in ascending score order. Means that lowest score got highest priority.
> SONAR-3321 Fix bug in file rename algorithm

- sonar-application/src/main/java/org/sonar/application/App.java
- sonar-application/src/test/java/org/sonar/application/AppTest.java
these temp file are especially used when uploading
> SONAR-7896 set env var TMPDIR to make JRuby use SQ tmp dir for tmp files

- server/sonar-server/src/main/java/org/sonar/server/license/ws/ListAction.java
- server/sonar-server/src/test/java/org/sonar/server/license/ws/ListActionTest.java
SONAR-8039 Return invalid server id when no server id generated and license not set to "*"
> SONAR-8039 Return invalid server id when no server id generated and license not set to "*"

- server/sonar-server/src/main/java/org/sonar/server/email/ws/SendAction.java
- server/sonar-server/src/main/java/org/sonar/server/notification/email/EmailNotificationChannel.java
- server/sonar-server/src/test/java/org/sonar/server/email/ws/SendActionTest.java
SONAR-7973 Do not return error 500 when email sending is failing
> SONAR-7973 Do not return error 500 when email sending is failing

- sonar-db/src/main/java/org/sonar/db/source/FileSourceDao.java
- sonar-db/src/main/java/org/sonar/db/version/v51/FeedFileSourcesBinaryData.java
- sonar-db/src/test/java/org/sonar/db/source/FileSourceDaoTest.java
- sonar-db/src/test/java/org/sonar/db/version/v51/FeedFileSourcesBinaryDataTest.java
This fixes:
* SONAR-8148 exception proof FeedFileSourcesBinaryData
* SONAR-8185 support at DAO level of null in FILES_SOURCES.LINES_HASHES
> DB related fixes for 5.6.3

- server/sonar-server/src/main/java/org/sonar/server/project/es/ProjectMeasuresIndexer.java
- server/sonar-server/src/main/java/org/sonar/server/project/es/ProjectMeasuresResultSetIterator.java
- server/sonar-server/src/test/java/org/sonar/server/project/es/ProjectMeasuresResultSetIteratorTest.java
The goal is to do nothing at startup when index already exist => No new row will be returned, nothing will be index
> SONAR-8221 Take into account date when indexing project measures at startup

- server/sonar-server/src/main/java/org/sonar/server/platform/web/RootFilter.java
When httpRequest.getSession(false) is called, the callers does not ask to create a http session.
(javadoc of HttpServletRequest: "If create is false and the request has no valid HttpSession, this method returns null.")
So throwing UnsupportedOperationException is not needed in this case and returning null is enough.
This will fix a [blocking issue](https://github.com/javamelody/sonar-javamelody/issues/4) in the [Sonar JavaMelody plugin](https://github.com/javamelody/javamelody/wiki/UserGuide#sonar-plugin).
> Do not throw UnsupportedOperationException when httpRequest.getSession(false) is called

- sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/GlobalSettings.java
- sonar-scanner-engine/src/main/java/org/sonar/scanner/genericcoverage/GenericTestExecutionReportParser.java
- sonar-scanner-engine/src/main/java/org/sonar/scanner/genericcoverage/GenericTestExecutionSensor.java
- sonar-scanner-engine/src/test/java/org/sonar/scanner/genericcoverage/GenericTestExecutionSensorTest.java
- sonar-scanner-engine/src/test/resources/mediumtest/xoo/sample-generic-test-exec/unittest.xml
- sonar-scanner-engine/src/test/resources/mediumtest/xoo/sample-generic-test-exec/unittest2.xml
* show warning in case of use of deprecated props
* deprecate root element 'unitTest' and support 'testExecutions'
* few other minor fixes
> SONAR-8314 Some rework on generic test executions report

- sonar-application/src/main/assembly/conf/wrapper.conf
Increase memory of app process to 8MB
> SONAR-8415 Low max memory of main process can lead to OOM in log Gobbler

- sonar-db/src/main/java/org/sonar/db/version/v60/PopulateProfileKeyOfActivities.java
- sonar-db/src/test/java/org/sonar/db/version/v60/PopulateProfileKeyOfActivitiesTest.java
delete ACTIVITY rows which don't have profileKey field
> SONAR-8534 Error in DB migration PopulateProfileKeyOfActivities in version 6.0

- server/sonar-server/src/main/java/org/sonar/server/authentication/BasicAuthenticator.java
- server/sonar-server/src/main/java/org/sonar/server/authentication/JwtCsrfVerifier.java
- server/sonar-server/src/main/java/org/sonar/server/authentication/RealmAuthenticator.java
- server/sonar-server/src/main/java/org/sonar/server/authentication/UserIdentityAuthenticator.java
- server/sonar-server/src/main/java/org/sonar/server/authentication/ws/LoginAction.java
- server/sonar-server/src/test/java/org/sonar/server/authentication/JwtCsrfVerifierTest.java
- server/sonar-server/src/test/java/org/sonar/server/authentication/RealmAuthenticatorTest.java
- server/sonar-server/src/test/java/org/sonar/server/authentication/UserIdentityAuthenticatorTest.java
for consistency, all message of AuthenticationException explicitly set in code has a upper case first char.
This can't be applied when message comes from a caught exception
> SONAR-8416 AuthenticationException message start with upper case

- stop.sh
I am recompiling and starting/stopping the server all day long. The usual error message `sh: 0: Can't open sonar-application/target/sonarqube-*/bin/linux-x86-64/sonar.sh` should be replaced by a better readable, in my opinion.
> better command line message if trying to stop without having compiled

- sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/ModuleScanContainer.java
This is making Java 3.13 fail, since it tries to inject Project.
> Fix Project missing in container

- server/sonar-ce/src/test/java/org/sonar/ce/container/ComputeEngineContainerImplTest.java
During my investigations about PurgeListener I ran into this malformed unit test calculation. I would love to fix it, so that I do not stumble over it in future developments again.
> SONAR-7282 fix module number count in ComputeEngineContainerImplTest

- server/sonar-web/src/main/js/apps/projects/components/PageSidebar.js
- server/sonar-web/src/main/js/apps/projects/filters/CoverageFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/DuplicationsFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/Filter.js
- server/sonar-web/src/main/js/apps/projects/filters/IssuesFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/LanguageFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/LanguageFilterOption.js
- server/sonar-web/src/main/js/apps/projects/filters/QualityGateFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/SizeFilter.js
- server/sonar-web/src/main/js/apps/projects/store/actions.js
- server/sonar-web/src/main/js/apps/projects/store/facetsDuck.js
- server/sonar-web/src/main/js/apps/projects/store/utils.js
- server/sonar-web/src/main/js/store/languages/reducer.js
- server/sonar-web/src/main/js/store/rootReducer.js
- server/sonar-web/src/main/less/components/search-navigator.less
The following additional filtering criterion should be added:
* Project languages (Java, JavaScript, PHP, ... )
* This filter should offer all the languages with LoC in the instance.
* The bar graph on the right of the filter should represent the count of projects with LoC of that language
* Multiple languages should be selectable at once as OR criteria
> SONAR-8875 Add language facet on projects page

- tests/upgrade/src/test/java/org/sonarsource/sonarqube/upgrade/UpgradeTest.java
Do not test URLs on old versions of SQ. Checks
are not valid.
> Improve reliability of UpgradeTest

- server/sonar-db-dao/src/main/java/org/sonar/db/qualityprofile/QualityProfileDao.java
- server/sonar-db-dao/src/main/java/org/sonar/db/qualityprofile/QualityProfileMapper.java
- server/sonar-db-dao/src/main/resources/org/sonar/db/qualityprofile/QualityProfileMapper.xml
- server/sonar-db-dao/src/test/java/org/sonar/db/component/ComponentDbTester.java
- server/sonar-db-dao/src/test/java/org/sonar/db/qualityprofile/QualityProfileDaoTest.java
- server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/ProjectsAction.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/DeleteActionTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/ProjectsActionTest.java
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/QProfilesWsTest.java
When searching for not yet associated projects of a quality profile, only projects of the same organization may be returned.
> SONAR-8857 api/qualityprofiles/projects must filter on org

- server/sonar-web/.eslintrc
- server/sonar-web/src/main/js/app/components/App.js
- server/sonar-web/src/main/js/app/components/LocalizationContainer.js
- server/sonar-web/src/main/js/app/components/nav/global/GlobalNavSearch.js
- server/sonar-web/src/main/js/apps/account/components/Tokens.js
- server/sonar-web/src/main/js/apps/account/notifications/Projects.js
- server/sonar-web/src/main/js/apps/account/organizations/CreateOrganizationForm.js
- server/sonar-web/src/main/js/apps/projects-admin/search.js
- server/sonar-web/src/main/js/apps/projects/components/ProjectTagsSelectorContainer.js
- server/sonar-web/src/main/js/apps/projects/filters/CoverageFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/DuplicationsFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/IssuesFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/LanguagesFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/QualityGateFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/SizeFilter.js
- server/sonar-web/src/main/js/apps/projects/filters/TagsFilter.js
- server/sonar-web/src/main/js/apps/quality-gates/components/Projects.js
- server/sonar-web/src/main/js/apps/quality-profiles/details/ProfileRules.js
- server/sonar-web/src/main/js/apps/users/components/UsersSearch.js
- server/sonar-web/src/main/js/components/SourceViewer/SourceViewerIssueLocations.js
- server/sonar-web/src/main/js/components/common/MultiSelect.js
- server/sonar-web/src/main/js/components/issue/Issue.js
With this we should order our components methods like this : 
1. type annotations
2. static methods
3. lifecycle stuff : 
1. propTypes and ci
2. constructor
3. lifecycle methods in right order
4. our custom methods
5. renderXYZ methods
6. render method
We can tweak this order as we want in the `sort-comp` rule if needed.
> Add format rule : react lifecycle methods should be ordered

- server/sonar-web/src/main/js/apps/coding-rules/components/CodingRulesAppContainer.js
- server/sonar-web/src/main/js/apps/coding-rules/init.js
- server/sonar-web/src/main/js/apps/coding-rules/models/state.js
- server/sonar-web/src/main/js/apps/coding-rules/rule-details-view.js
- server/sonar-web/src/main/js/apps/coding-rules/rule/custom-rule-view.js
- server/sonar-web/src/main/js/apps/coding-rules/rule/custom-rules-view.js
- server/sonar-web/src/main/js/apps/coding-rules/rule/rule-description-view.js
- server/sonar-web/src/main/js/apps/coding-rules/rule/rule-meta-view.js
Custom rules and rule customizations must be available only for the default organization (or when organizations are disabled, i.e. on premise).
> SONAR-9005 disable custom rules for custom orgs

- server/sonar-server/src/main/java/org/sonar/server/rule/RuleDeleter.java
- server/sonar-server/src/main/java/org/sonar/server/rule/ws/CreateAction.java
- server/sonar-server/src/test/java/org/sonar/server/rule/RuleDeleterTest.java
- server/sonar-server/src/test/java/org/sonar/server/rule/ws/CreateActionTest.java
As of #1949, template rules and custom rules will be removed, when you enable organizations. The checks on api/rules/create and api/rules/delete are now redundant.
> SONAR-9132 remove redundant "org-enabled" check for custom rule create/delete

- server/sonar-server/src/main/java/org/sonar/server/component/index/ComponentIndex.java
- server/sonar-server/src/test/java/org/sonar/server/component/index/ComponentIndexScoreTest.java
api/components/suggestions used to only use "relevance" (score) in sorting results. If two suggestions have exactly the same relevance (this is a rare case), then we will now also take alphabetical order into account.
> SONAR-9217 if two component suggestions have the same relevancy, prefer A over Z

- server/sonar-server/src/main/java/org/sonar/server/component/ws/SuggestionsAction.java
- server/sonar-server/src/test/java/org/sonar/server/component/ws/SuggestionsActionTest.java
The attribute will be omitted for views, subviews and projects, but included for modules, files and test-files.
> SONAR-9078 only include attr. "project" for certain types of suggestions

- server/sonar-server/src/main/java/org/sonar/server/component/ws/SuggestionsAction.java
- server/sonar-server/src/main/java/org/sonar/server/es/textsearch/ComponentTextSearchFeatureRepertoire.java
- server/sonar-server/src/main/java/org/sonar/server/es/textsearch/ComponentTextSearchQueryFactory.java
- server/sonar-server/src/test/java/org/sonar/server/component/ws/SuggestionsActionTest.java
The search for suggestions should ignore tokens, that are only one character long (with warning), but use all other tokens for the search.
> SONAR-9072 for api/components/suggestions use all valid search tokens

- it/it-tests/src/test/java/it/organization/OrganizationMembershipTest.java
The two fixed tests were sometime failing, probably when the randomly generated user name was sorted before the "Admin" user.
> Fix unconsistant IT's in organization membership

- server/sonar-web/src/main/js/helpers/l10n.js
(Note this is actually not tested, so I don't know whether it fixes the issue completely)
Related to #1151
> Do not break if navigator.language == undefined

- sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/BranchConfigurationValidator.java
- sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/DefaultBranchConfigurationValidator.java
- sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/ProjectReactorValidator.java
Notes:
- `ProjectReactorValidator` already had analysis mode param, no need to inject anything more
- Btw: could not drop `DefaultBranchConfigurationValidator` (injected in `ProjectReactorValidator` constructor), because Pico's `@Nullable` is not effective in constructors, only in providers (Pico complains if it cannot find implementation)
- Did not add a medium test, because it seems to me that any user of `ScannerMediumTester` should already reveal injection issues, as it already uses a fake `BranchConfigurationLoader`.
> Validate branch + incremental configuration

- tests/src/test/java/org/sonarqube/tests/projectAdministration/ProjectQualityGatePageTest.java
This tries to fix false positives on QualityGateTest::does_not_fail_when_condition_is_on_removed_metric
> make quality gate ITs more reliable, by unsetting default qg

- pom.xml
When a call-site passes a subject for an email that contains line-breaks in Apache Commons Email 1.0 through 1.4, the caller can add arbitrary SMTP headers.	
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-9801
> CVE-2017-9801 (commons-email)

- tests/src/test/java/org/sonarqube/tests/qualityGate/QualityGateTest.java
This tries to fix false positives on QualityGateTest::does_not_fail_when_condition_is_on_removed_metric
> make quality gate ITs more reliable, by not using default qg (2)

- sonar-application/src/main/assembly/conf/sonar.properties
in sonar.properties. "Kopf" is not compatible with Elasticsearch 5 and therefore should not be mentioned.
> fix the documentation of the Elasticsearch http port setting

- server/sonar-web/src/main/js/components/ui/Level.css
Fixing problem with localazed string in level label.  
Before:  
After:   
In En local size is not changed:
> .level label localazed size css fix

- server/sonar-process/src/main/java/org/sonar/process/ProcessProperties.java
- server/sonar-process/src/main/java/org/sonar/process/es/EsSettings.java
- server/sonar-process/src/test/java/org/sonar/process/es/EsSettingsTest.java
"sonar.search.marvelHosts" was an internal property, used to enable marvel managing of the embedded Elasticsearch process.
> dropped marvel property

- sonar-core/src/main/java/org/sonar/core/metric/ScannerMetrics.java
- sonar-core/src/test/java/org/sonar/core/metric/ScannerMetricsTest.java
I did not add logging, because I just don't see the point. If somebody is expecting metrics from a plugin, they had better check that it actually provides some. Logging would require either that I add a side effect while mapping the stream of metrics providers, or an extra iteration over all providers. Neither is great, and I think it would be unnecessary ugliness just for the sake of faulty plugins that should have been better implemented and tested.
> SONAR-9685 Better handle when a plugin returns null from Metrics::getMetrics

- server/sonar-ce/src/main/java/org/sonar/ce/logging/ChangeLogLevelHttpAction.java
- server/sonar-ce/src/main/java/org/sonar/ce/taskprocessor/CeProcessingSchedulerImpl.java
- server/sonar-db-dao/src/main/java/org/sonar/db/DBSessionsImpl.java
- server/sonar-server/src/main/java/org/sonar/server/health/DbConnectionNodeCheck.java
- server/sonar-server/src/main/java/org/sonar/server/notification/email/EmailNotificationChannel.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/PluginDownloader.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/StaticResourcesServlet.java
- server/sonar-server/src/test/java/org/sonar/server/plugins/StaticResourcesServletTest.java
The `org.sonar.api.utils.log.Logger` interface supports logging instances of exception/throwable directly at the warn and error levels, but not at the trace, debug, or info levels. Instead, at the trace, debug, or info levels, the exception/throwable must be formatted as a regular format arg (Object).
> Fix some logger calls

- quick-build.sh
-DskipTests just skips the test execution: the tests are still compiled. Where as-Dmaven.test.skip will skip both compilation and execution of the tests.
> Skip compiling Test classes

- server/sonar-db-core/pom.xml
- server/sonar-db-core/src/test/java/org/sonar/db/CoreTestDb.java
- server/sonar-db-dao/pom.xml
- server/sonar-db-dao/src/test/resources/logback-test.xml
- server/sonar-process/src/test/java/org/sonar/process/LoggingRule.java
- server/sonar-process/src/test/resources/logback-test.xml
- server/sonar-process/src/test/resources/org/sonar/process/logback-test.xml
- server/sonar-server/pom.xml
- server/sonar-server/src/test/resources/logback-test.xml
- sonar-plugin-api/pom.xml
- sonar-plugin-api/src/test/resources/logback-test.xml
- sonar-scanner-engine/src/test/resources/logback-test.xml
basically remove 300Kb of lines starting with "|-" spit by logback at INFO level but which are really debug information (operations performed by logback)
also fix unstable test `SharedHealthStateImplTest`
> fix build logback verbosity

- server/sonar-qa-util/src/main/java/org/sonarqube/qa/util/pageobjects/QualityProfilePage.java
- server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/SearchAction.java
- server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/SearchData.java
- server/sonar-server/src/main/resources/org/sonar/server/qualityprofile/ws/search-example.json
- server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/SearchActionTest.java
- server/sonar-web/src/main/js/api/quality-profiles.ts
- server/sonar-web/src/main/js/apps/quality-profiles/components/BuiltInQualityProfileBadge.tsx
- server/sonar-web/src/main/js/apps/quality-profiles/components/ProfileActions.tsx
- server/sonar-web/src/main/js/apps/quality-profiles/components/__tests__/ProfileActions-test.tsx
- server/sonar-web/src/main/js/apps/quality-profiles/components/__tests__/__snapshots__/ProfileActions-test.tsx.snap
- server/sonar-web/src/main/js/apps/quality-profiles/details/ProfileProjects.tsx
- sonar-ws/src/main/protobuf/ws-qualityprofiles.proto
- tests/src/test/java/org/sonarqube/tests/qualityProfile/OrganizationQualityProfilesUiTest.java
- tests/src/test/java/org/sonarqube/tests/qualityProfile/QualityProfilesEditTest.java
In api/qualityprofiles/search, the following actions are now availables :
- delete : Available when not built-it, not default, and have either QP admin permission or have rights to edit
- associateProjects : Available when not default and have either QP admin permission or have rights to edit
> SONAR-10074 Add QP actions "delete" and "associateProjects"

- server/sonar-web/src/main/js/apps/quality-profiles/details/ProfileExporters.tsx
The name of this parameter was updated in this commit, but was never corrected on the UI: https://github.com/SonarSource/sonarqube/commit/184dbe792ce14f192f75b13507c30a4b697d5852
This was encountered on SonarQube version 6.7
> Update profile name parameter

- server/sonar-web/src/main/js/api/web-api.ts
- server/sonar-web/src/main/js/apps/overview/meta/Meta.js
- server/sonar-web/src/main/js/apps/overview/stickers/StickerParams.tsx
- server/sonar-web/src/main/js/apps/overview/stickers/StickersModal.tsx
- server/sonar-web/src/main/js/apps/overview/stickers/__tests__/StickerParams-test.tsx
- server/sonar-web/src/main/js/apps/overview/stickers/__tests__/StickersModal-test.tsx
- server/sonar-web/src/main/js/apps/overview/stickers/__tests__/__snapshots__/StickerParams-test.tsx.snap
- server/sonar-web/src/main/js/apps/overview/stickers/__tests__/__snapshots__/StickersModal-test.tsx.snap
- server/sonar-web/src/main/js/apps/overview/stickers/__tests__/utils-test.ts
- server/sonar-web/src/main/js/apps/overview/stickers/utils.ts
- server/sonar-web/src/main/js/apps/web-api/components/ResponseExample.tsx
- server/sonar-web/src/main/js/apps/web-api/components/WebApiApp.tsx
- sonar-core/src/main/resources/org/sonar/l10n/core.properties
@stas-vilchik Currently the two WS are not yet ready, they are mocks. So when choosing a different metric you wont see the badge change (only the url) and it's the wrong image that is displayed as the second badge.
So if you prefer you can wait a bit until the WS are merged on master and I rebase. Julien is targeting to merge around noon.
> Add standard badges

- server/sonar-ce/src/main/java/org/sonar/ce/container/CePluginRepository.java
- server/sonar-ce/src/test/java/org/sonar/ce/container/CePluginRepositoryTest.java
- server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/step/LoadReportAnalysisMetadataHolderStep.java
- server/sonar-server/src/main/java/org/sonar/server/plugins/ServerPluginJarExploder.java
- server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/LoadReportAnalysisMetadataHolderStepTest.java
- sonar-core/src/main/java/org/sonar/core/platform/PluginRepository.java
This pull request does not fix the root problem. Backdating of issues may be incorrect if a plugin is badly considered as uninstalled. However it prevents the task to randomly fail.
> SONAR-10315 CE task fails when a plugin has been uninstalled after project analysis

- sonar-application/src/main/assembly/conf/sonar.properties
Make it consistent with the two other javaOpts settings, avoiding errors due to only uncommenting one of the three lines.
Without exaggeration I spent three hours troubleshooting due to having uncommented only the top line.
> Put ES javaOpts arguments on one line

- sonar-plugin-api/src/main/java/org/sonar/api/batch/sensor/highlighting/internal/DefaultHighlighting.java
I noticed a typo in the DefaultHighlighting class, so here's a fix.
> Corrected typo

- server/sonar-server/src/main/java/org/sonar/server/authentication/OAuth2Redirection.java
- server/sonar-server/src/test/java/org/sonar/server/authentication/OAuth2RedirectionTest.java
- server/sonar-web/src/main/js/apps/maintenance/main-view.js
- server/sonar-web/src/main/js/apps/sessions/components/LoginFormContainer.tsx
- server/sonar-web/src/main/js/helpers/__tests__/urls-test.ts
- server/sonar-web/src/main/js/helpers/urls.ts
- tests/src/test/java/org/sonarqube/tests/user/OAuth2IdentityProviderTest.java
> SONAR-11475 Check if url is relative before redirecting

- sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/ProjectReactorBuilder.java
Use stopInfo() instead of stopDebug() for Process project properties, so that the log of scanner are paired.
Please review our [contribution guidelines](https://github.com/SonarSource/sonarqube/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:
> use stopInfo() instead of stopDebug()
