server/sonar-server/src/main/java/org/sonar/server/ui/JRubyFacade.java, server/sonar-web/src/main/webapp/WEB-INF/app/controllers/batch_bootstrap_controller.rb, sonar-core/src/main/java/org/sonar/core/preview/PreviewCache.java, sonar-core/src/test/java/org/sonar/core/preview/PreviewCacheTest.java
SONAR-6083 Server OutOfMemory error with preview analysis mode
=> SONAR-6083 Server OutOfMemory error with preview analysis mode

server/sonar-web/src/main/webapp/WEB-INF/app/controllers/api/timemachine_controller.rb
=> SONAR-5183 timezones - fix timemachine ruby code

sonar-core/src/main/java/org/sonar/core/purge/PurgeDao.java, sonar-core/src/test/java/org/sonar/core/purge/PurgeDaoTest.java
port of fix made on 4.5 https://github.com/SonarSource/sonarqube/commit/1472cab922e3fb54b8a445359b02988b96d4efad
=> SONAR-6130 fix deadlock during purge

server/sonar-server/src/main/java/org/sonar/server/batch/ProjectRepositoryLoader.java, server/sonar-server/src/main/java/org/sonar/server/user/UserSession.java, server/sonar-server/src/test/java/org/sonar/server/batch/ProjectRepositoryLoaderMediumTest.java
SONAR-6009 Each time the batch call the project referentials WS, a E/S query is executed for each rule
=> SONAR-6009 Each time the batch call the project referentials WS, a E/S query is executed for each rule

server/sonar-web/src/main/webapp/WEB-INF/app/controllers/sessions_controller.rb, server/sonar-web/src/main/webapp/WEB-INF/app/views/sessions/login.html.erb
SONAR-5659 Issues link parameters disappear when fail to log
=> SONAR-5659 Issues link parameters disappear when fail to log

server/sonar-web/src/main/webapp/WEB-INF/app/models/project_measure.rb
SONAR-6222 SQALE Rating is badly render in the timeline widget
=> SONAR-6222 SQALE Rating is badly render in the timeline widget

server/sonar-server/src/main/java/org/sonar/server/user/ws/UsersWs.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/UsersWsTest.java
SONAR-6214 Document parameter 's' of api/users/search
=> SONAR-6214 Document parameter 's' of api/users/search

server/sonar-server/src/main/java/org/sonar/server/issue/notification/DoNotFixNotificationDispatcher.java, server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/DoNotFixNotificationDispatcherTest.java, sonar-core/src/main/resources/org/sonar/l10n/core.properties
SONAR-4624 complete "new FP issues" with resolution "won't fix"
-> dispatcher becomes "Issues resolved as false positive or won't fix"
=> SONAR-4624 complete "new FP issues" with resolution "won't fix"

server/sonar-web/src/main/webapp/WEB-INF/config/environment.rb, server/sonar-web/src/main/webapp/WEB-INF/db/migrate/540_create_activities_table.rb, server/sonar-web/src/main/webapp/WEB-INF/db/migrate/718_add_issue_long_dates.rb, server/sonar-web/src/main/webapp/WEB-INF/db/migrate/720_rename_issue_long_dates.rb, server/sonar-web/src/main/webapp/WEB-INF/db/migrate/721_remove_sort_field_from_issue_filters.rb
Reentrant db migrations when adding/removing columns or tables
=> Reentrant db migrations when adding/removing columns or tables

server/sonar-server/src/main/java/org/sonar/server/batch/IssuesAction.java, server/sonar-server/src/main/java/org/sonar/server/batch/ProjectRepositoryLoader.java, server/sonar-server/src/main/java/org/sonar/server/component/db/ComponentDao.java, server/sonar-server/src/main/java/org/sonar/server/view/index/ViewIndexer.java, server/sonar-server/src/test/java/org/sonar/server/batch/IssuesActionTest.java, server/sonar-server/src/test/java/org/sonar/server/component/db/ComponentDaoTest.java, server/sonar-server/src/test/resources/org/sonar/server/component/db/ComponentDaoTest/multi-modules.xml, sonar-core/src/main/java/org/sonar/core/component/db/ComponentMapper.java, sonar-core/src/main/java/org/sonar/core/properties/PropertiesDao.java, sonar-core/src/main/java/org/sonar/core/properties/PropertiesMapper.java, sonar-core/src/main/resources/org/sonar/core/component/db/ComponentMapper.xml, sonar-core/src/main/resources/org/sonar/core/properties/PropertiesMapper.xml, sonar-core/src/test/java/org/sonar/core/properties/PropertiesDaoTest.java
SONAR-6012 Issues on files on removed modules should contain the module key
=> SONAR-6012 Issues on files on removed modules should contain the module key

server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistSymbolsStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistSymbolsStepTest.java, sonar-batch-protocol/src/main/gen-java/org/sonar/batch/protocol/output/BatchReport.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/BatchReportReader.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/BatchReportWriter.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/FileStructure.java, sonar-batch-protocol/src/main/protobuf/batch_report.proto, sonar-batch-protocol/src/test/java/org/sonar/batch/protocol/output/BatchReportReaderTest.java, sonar-batch-protocol/src/test/java/org/sonar/batch/protocol/output/BatchReportWriterTest.java
=> SONAR-6320 Symbol in compute

server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistCoverageStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistCoverageStepTest.java, sonar-batch-protocol/src/main/gen-java/org/sonar/batch/protocol/Constants.java, sonar-batch-protocol/src/main/gen-java/org/sonar/batch/protocol/input/BatchInput.java, sonar-batch-protocol/src/main/gen-java/org/sonar/batch/protocol/output/BatchReport.java, sonar-batch-protocol/src/main/gen-java/org/sonar/server/source/db/FileSourceDb.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/BatchReportReader.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/BatchReportWriter.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/FileStructure.java, sonar-batch-protocol/src/main/protobuf/batch_report.proto, sonar-batch-protocol/src/test/java/org/sonar/batch/protocol/output/BatchReportReaderTest.java, sonar-batch-protocol/src/test/java/org/sonar/batch/protocol/output/BatchReportWriterTest.java
SONAR-6338 Coverage in compute
=> SONAR-6338 Coverage in compute

server/sonar-server/src/main/java/org/sonar/server/computation/step/ComputationSteps.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistNumberOfDaysSinceLastCommitStep.java, server/sonar-server/src/main/java/org/sonar/server/source/index/SourceLineIndex.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ComputationStepsTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistDuplicationMeasuresStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistNumberOfDaysSinceLastCommitStepTest.java, server/sonar-server/src/test/java/org/sonar/server/source/index/SourceLineIndexTest.java, server/sonar-server/src/test/resources/org/sonar/server/computation/step/PersistNumberOfDaysSinceLastCommitStepTest/insert-from-index-result.xml, server/sonar-server/src/test/resources/org/sonar/server/computation/step/PersistNumberOfDaysSinceLastCommitStepTest/insert-from-report-result.xml, sonar-plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java
end to end test done: check the measure is correctly computed for a given project in the « Measures » page.
=> 'Days since last commit' metric in platform out of the box - SONAR-6353

server/sonar-server/src/main/java/org/sonar/server/computation/source/HighlightingLineReader.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistFileSourcesStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/source/HighlightingLineReaderTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistFileSourcesStepTest.java
SONAR-6258 Persist highlighting into file sources
=> SONAR-6258 Persist highlighting into file sources

server/sonar-server-benchmarks/src/test/java/org/sonar/server/benchmark/SourceDbBenchmarkTest.java, server/sonar-server/src/main/java/org/sonar/server/computation/source/ComputeFileSourceData.java, server/sonar-server/src/main/java/org/sonar/server/computation/source/HighlightingLineReader.java, server/sonar-server/src/main/java/org/sonar/server/computation/source/RangeOffsetHelper.java, server/sonar-server/src/main/java/org/sonar/server/computation/source/SymbolsLineReader.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/ComputationSteps.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/IndexSourceLinesStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistFileSourcesStep.java, server/sonar-server/src/main/java/org/sonar/server/es/BaseIndexer.java, server/sonar-server/src/main/java/org/sonar/server/source/index/SourceFileResultSetIterator.java, server/sonar-server/src/main/java/org/sonar/server/source/index/SourceLineIndexer.java, server/sonar-server/src/test/java/org/sonar/server/computation/source/ComputeFileSourceDataTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/source/HighlightingLineReaderTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/source/RangeOffsetHelperTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/source/SymbolsLineReaderTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ComputationStepsTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/IndexSourceLinesStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistFileSourcesStepTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/index/IssueAuthorizationIndexerTest.java, server/sonar-server/src/test/java/org/sonar/server/source/index/SourceFileResultSetIteratorTest.java, server/sonar-server/src/test/java/org/sonar/server/source/index/SourceLineIndexerTest.java, server/sonar-server/src/test/resources/org/sonar/server/computation/step/IndexSourceLinesStepTest/index_source.xml, server/sonar-server/src/test/resources/org/sonar/server/computation/step/IndexSourceLinesStepTest/update_source_date_on_sources_with_update_at_to_zero-result.xml, server/sonar-server/src/test/resources/org/sonar/server/source/index/SourceFileResultSetIteratorTest/filter_by_project.xml, server/sonar-server/src/test/resources/org/sonar/server/source/index/SourceFileResultSetIteratorTest/filter_by_project_and_date.xml, sonar-batch-protocol/src/main/gen-java/org/sonar/server/source/db/FileSourceTestDb.java, sonar-batch/src/main/java/org/sonar/batch/index/SourcePersister.java
SONAR-6258 Fix hashes, symbols and highlighting persistence
=> SONAR-6258 Fix hashes, symbols and highlighting persistence

server/sonar-server/src/main/java/org/sonar/server/plugins/ws/InstalledPluginsWsAction.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/package-info.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-installed_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/InstalledPluginsWsActionTest.java, sonar-plugin-api/src/main/java/org/sonar/api/utils/text/JsonWriter.java, sonar-plugin-api/src/test/java/org/sonar/api/utils/text/JsonWriterTest.java
This PR : 
* changes the WS response to use a root object so that the response can be easily extended in the future (best practice)
* adds more properties to the WS response for each plugin
=> SONAR-6376 better Java WS to list installed plugins

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PendingPluginsWsAction.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-pending_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PendingPluginsWsActionTest.java
once backing components have been updated to read plugin's jarfile manifests, more information will be added to the JSON response
=> SONAR-6383 add java WS listing pending plugin installs and removal

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/AvailablePluginsWsAction.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/UpdatePluginsWsAction.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/UpdatePluginsWsActionTest.java
updates a plugin to its latest compatible version
=> SONAR-6382 add Java ws to update a plugin

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/AvailablePluginsWsAction.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginWSCommons.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/UpdatesPluginsWsAction.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-updates_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/AbstractUpdateCenterBasedPluginsWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/AvailablePluginsWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginWSCommonsTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/UpdatesPluginsWsActionTest.java, server/sonar-server/src/test/resources/org/sonar/server/plugins/ws/UpdatablePluginsWsActionTest/properties_per_plugin.json
This PR:
* adds a new WS to list installed plugins for which a newer version is available
* adds explicit sorting of plugins in response of available WS (done in this PR because code is common with updatable WS)
=> SONAR-6379 add Java WS to list plugin updates

server/sonar-server/src/main/java/org/sonar/server/db/migrations/PlatformDatabaseMigration.java, server/sonar-server/src/test/java/org/sonar/server/db/migrations/PlatformDatabaseMigrationConcurrentAccessTest.java
this will also make unit test stable
=> SONAR-6366 improve handling of really simultaneous db migration calls

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/InstallPluginsWsAction.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/InstallPluginsWsActionTest.java
just the WS glue to the underlying components.
note : only the latest version of the plugin can be installed
=> SONAR-6381 add java WS to install a plugin

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/UninstallPluginsWsAction.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/UninstallPluginsWsActionTest.java
add a Java WS to uninstall an installed plugin
=> SONAR-6380 add Java WS to uninstall a plugin

server/sonar-server/src/main/java/org/sonar/server/plugins/ws/UpdatePluginsWsAction.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/UpdatePluginsWsActionTest.java
PR to take blocking comment of #244 into account after accidental merge
=> SONAR-6382 updating plugin is restricted to system admins

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/UpgradesSystemWsAction.java, server/sonar-server/src/main/resources/org/sonar/server/platform/ws/example-updates_plugins.json, server/sonar-server/src/test/java/org/sonar/server/platform/ws/UpgradesSystemWsActionTest.java
I'll investigate why I have imports reodered on my laptop before merging to master
=> SONAR-6385 add WS to list SonarQube upgrades

server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginWSCommons.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-installed_plugins.json, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-pending_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/InstalledPluginsWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PendingPluginsWsActionTest.java, sonar-core/src/main/java/org/sonar/core/plugins/DefaultPluginMetadata.java, sonar-plugin-api/src/main/java/org/sonar/api/platform/PluginMetadata.java
information added to response of WS listing installed pluging and pending operations on plugins
=> SONAR-6430 add plugin source revision to JSON response

server/sonar-server/src/main/java/org/sonar/server/plugins/ws/AvailablePluginsWsAction.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginWSCommons.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ws/UpdatesPluginsWsAction.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-available_plugins.json, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-updates_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/AvailablePluginsWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginWSCommonsTest.java, server/sonar-server/src/test/resources/org/sonar/server/plugins/ws/AvailablePluginsWsActionTest/properties_per_plugin.json
* rename status in `/plugins/available` and document it
* remove artifact from `/plugins/available` and `/plugins/updates` response (shared code)
=> SONAR-6377 apply po feedback

server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginWSCommons.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-updates_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginWSCommonsTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/UpdatesPluginsWsActionTest.java
+ fix broken br tag in action description
removal of artifact from JSON response is done in PR #266
=> add release description and changeLogUrl in JSON response of /plugins/updates

server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PluginWSCommons.java, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-installed_plugins.json, server/sonar-server/src/main/resources/org/sonar/server/plugins/ws/example-pending_plugins.json, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/InstalledPluginsWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PendingPluginsWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginWSCommonsTest.java
remove artifact from JSON response of WS `/plugins/installed` and `/plugins/pending`
=> SONAR-6376 SONAR-6383 remove artifact from JSON response

server/sonar-server/src/main/java/org/sonar/server/platform/ws/UpgradesSystemWsAction.java, server/sonar-server/src/main/resources/org/sonar/server/platform/ws/example-upgrades_plugins.json, server/sonar-server/src/test/java/org/sonar/server/platform/ws/UpgradesSystemWsActionTest.java
use common code to write plugin properties in JSON response of `/api/system/upgrades`
=> SONAR-6365 consistent properties for plugin in JSON response

server/sonar-server/src/main/java/org/sonar/server/db/migrations/PlatformDatabaseMigration.java, server/sonar-server/src/main/java/org/sonar/server/exceptions/ForbiddenException.java, server/sonar-server/src/main/java/org/sonar/server/platform/Platform.java, server/sonar-server/src/main/java/org/sonar/server/platform/ServerComponents.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/MigrateDbSystemWsAction.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/ServerWsAction.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/SystemInfoWsAction.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/SystemRestartWsAction.java, server/sonar-server/src/main/java/org/sonar/server/ruby/CallDatabaseVersionUpgrade.java, server/sonar-server/src/main/java/org/sonar/server/ruby/CallLoadJavaWebServices.java, server/sonar-server/src/main/java/org/sonar/server/ruby/PlatformRubyBridge.java, server/sonar-server/src/main/java/org/sonar/server/ruby/RubyRailsRoutes.java, server/sonar-server/src/main/java/org/sonar/server/ui/JRubyFacade.java, server/sonar-server/src/main/resources/org/sonar/server/platform/ws/example-migrate_db.json, server/sonar-server/src/main/resources/org/sonar/server/ruby/call_databaseversion_upgrade.rb, server/sonar-server/src/main/resources/org/sonar/server/ruby/call_load_java_web_services.rb, server/sonar-server/src/main/resources/org/sonar/server/ruby/call_upgrade_and_start.rb, server/sonar-server/src/test/java/org/sonar/server/db/migrations/PlatformDatabaseMigrationAsynchronousTest.java, server/sonar-server/src/test/java/org/sonar/server/db/migrations/PlatformDatabaseMigrationConcurrentAccessTest.java, server/sonar-server/src/test/java/org/sonar/server/db/migrations/PlatformDatabaseMigrationTest.java, server/sonar-server/src/test/java/org/sonar/server/platform/ws/MigrateDbSystemWsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/platform/ws/ServerWsTest.java, server/sonar-server/src/test/java/org/sonar/server/ruby/PlatformRubyBridgeTest.java, server/sonar-server/src/test/java/org/sonar/server/tester/ServerTester.java, server/sonar-server/src/test/resources/org/sonar/server/ruby/database_version.rb, server/sonar-web/src/main/webapp/WEB-INF/app/controllers/api/java_ws_controller.rb, server/sonar-web/src/main/webapp/WEB-INF/app/controllers/api/server_controller.rb, server/sonar-web/src/main/webapp/WEB-INF/app/controllers/application_controller.rb, server/sonar-web/src/main/webapp/WEB-INF/lib/database_version.rb
this PR adds the new WS server/migrate
this PR is the same as #202, but recreated based on master
IT tests are currently failing because restarting the Java WS after db upgrade does not work anymore
=> SONAR-6366 new ws for db migration

server/sonar-server/src/main/java/org/sonar/server/issue/notification/AbstractNewIssuesEmailTemplate.java, server/sonar-server/src/main/java/org/sonar/server/issue/notification/MyNewIssuesEmailTemplate.java, server/sonar-server/src/main/java/org/sonar/server/issue/notification/MyNewIssuesNotification.java, server/sonar-server/src/main/java/org/sonar/server/issue/notification/NewIssuesNotification.java, server/sonar-server/src/main/java/org/sonar/server/issue/notification/NewIssuesNotificationFactory.java, server/sonar-server/src/main/java/org/sonar/server/issue/notification/NewIssuesStatistics.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/MyNewIssuesEmailTemplateTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/MyNewIssuesNotificationTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/NewIssuesEmailTemplateTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/NewIssuesNotificationTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/NewIssuesStatisticsTest.java, server/sonar-server/src/test/resources/org/sonar/server/issue/notification/MyNewIssuesEmailTemplateTest/email_with_all_details.txt, server/sonar-server/src/test/resources/org/sonar/server/issue/notification/NewIssuesEmailTemplateTest/email_with_all_details.txt
please check also: https://github.com/SonarSource/sonar-tests-core/pull/6
=> add top 5 rules on 'New Issues' and 'My New Issues' notifications - SONAR-6045

server/sonar-server/src/main/java/org/sonar/server/computation/ReportQueue.java, server/sonar-server/src/main/java/org/sonar/server/computation/ws/QueueAction.java, server/sonar-server/src/main/java/org/sonar/server/computation/ws/SubmitReportAction.java, server/sonar-server/src/test/java/org/sonar/server/computation/ReportQueueTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/db/AnalysisReportDaoTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/ws/QueueActionTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/ws/SubmitReportActionTest.java, server/sonar-server/src/test/resources/org/sonar/server/computation/db/AnalysisReportDaoTest/insert-result.xml, server/sonar-server/src/test/resources/org/sonar/server/computation/db/AnalysisReportDaoTest/select.xml, server/sonar-server/src/test/resources/org/sonar/server/computation/ws/QueueActionTest/list_queue_reports.json, sonar-core/src/main/java/org/sonar/core/computation/db/AnalysisReportDto.java, sonar-core/src/main/resources/org/sonar/core/computation/db/AnalysisReportMapper.xml
Add project name in compute report queue
=> Add project name in compute report queue

server/sonar-server/src/main/java/org/sonar/server/batch/BatchWsModule.java, server/sonar-server/src/main/java/org/sonar/server/db/migrations/MigrationStep.java, server/sonar-server/src/main/java/org/sonar/server/db/migrations/MigrationStepModule.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel1.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel2.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel3.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevelSafeMode.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevelStartup.java, server/sonar-server/src/main/java/org/sonar/server/search/EsSearchModule.java, server/sonar-server/src/test/java/org/sonar/server/batch/BatchWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/db/migrations/MigrationStepModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/search/EsSearchModuleTest.java, server/sonar-web/src/main/webapp/WEB-INF/db/migrate/README.txt, sonar-core/src/main/java/org/sonar/core/component/Module.java, sonar-core/src/main/java/org/sonar/core/platform/ComponentContainer.java
this PR introduces the concept of module as a group of components
this will allow reducing length of the ComponentLevel classes and in the near future implement lazy start of components and/or description of implicit component dependencies
this PR also includes a few module to demo usage and as a proof-of-concept
=> add module concept

server/sonar-web/pom.xml
@stas-vilchik Can you take a look at this please?
=> Active fast grunt build in dev mode

server/sonar-server/src/main/java/org/sonar/server/permission/PermissionQueryParser.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/QGatesWs.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/ProjectsAction.java, server/sonar-server/src/main/java/org/sonar/server/user/ws/GroupsAction.java, server/sonar-server/src/main/java/org/sonar/server/usergroups/ws/UsersAction.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/GroupsActionTest.java, server/sonar-server/src/test/java/org/sonar/server/usergroups/ws/UsersActionTest.java, sonar-plugin-api/src/main/java/org/sonar/api/server/ws/WebService.java
This PR is a first step to get feedback; the refactoring will be applied on other WS declarations if deemed suitable.
=> Refactor WS selection mode for users and groups

sonar-batch/src/main/java/org/sonar/batch/bootstrap/PersistentCacheProvider.java, sonar-batch/src/test/java/org/sonar/batch/bootstrap/PersistentCacheProviderTest.java
=> SONAR-6577 offline mode in preview mode

server/sonar-server/src/main/java/org/sonar/server/computation/debt/Characteristic.java, server/sonar-server/src/main/java/org/sonar/server/computation/debt/package-info.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/BatchMeasureToMeasure.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/Measure.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureDtoToMeasure.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureRepository.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureRepositoryImpl.java, server/sonar-server/src/test/java/org/sonar/server/computation/debt/CharacteristicTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureRepositoryImplTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureToMeasureDtoTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/QualityGateEventsStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/QualityProfileEventsStepTest.java
this PR:
* makes `Measure` class immutable
* adds full support for `Measure` associated to a rule or a characteristic
* adds the `update` method
* fix some quality flaws encountered on the way
=> add update method to MeasureRepository

server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureRepositoryImpl.java
side effect: Measure returned by getRawMeasures can now be updated
=> now fully cache measures from batch in MeasureRepository

server/sonar-server/src/main/java/org/sonar/server/computation/container/ComputeEngineContainerImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/language/LanguageRepositoryImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/language/PlatformLanguageRepository.java, server/sonar-server/src/test/java/org/sonar/server/computation/language/LanguageRepositoryImplTest.java
fix platform language repository injection when there is no language plugin in SQ + rename it
=> fix platform language repository + rename it

server/sonar-server/src/main/java/org/sonar/server/computation/container/ComputeEngineContainerImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/CoreFormulaRepositoryImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/ComputeFormulaMeasuresStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/formula/CoreFormulaRepositoryImplTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ComputeFormulaMeasuresStepTest.java, sonar-batch/src/test/java/org/sonar/batch/mediumtest/measures/MeasuresMediumTest.java, sonar-batch/src/test/java/org/sonar/batch/sensor/DefaultSensorStorageTest.java, sonar-plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java, sonar-plugin-api/src/main/java/org/sonar/api/measures/Metric.java
SONAR-6605 Replace some batch formulas by compute formulas
=> SONAR-6605 Replace some batch formulas by compute formulas

server/sonar-server/src/main/java/org/sonar/server/computation/step/ComputeQProfileMeasureStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ComputeQProfileMeasureStepTest.java, sonar-batch/src/main/java/org/sonar/batch/repository/DefaultProjectRepositoriesLoader.java, sonar-batch/src/test/java/org/sonar/batch/repository/DefaultProjectRepositoriesLoaderTest.java
SONAR-6729 Analysis should fail when no quality profile
=> SONAR-6729 Analysis should fail when no quality profile

pom.xml, server/pom.xml, server/sonar-server/pom.xml, server/sonar-server/src/main/java/org/sonar/server/platform/Platform.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevelStartup.java, server/sonar-server/src/main/java/org/sonar/server/view/bridge/ViewsBootstrap.java, server/sonar-server/src/main/java/org/sonar/server/view/bridge/ViewsStopper.java, server/sonar-server/src/test/java/org/sonar/server/platform/ViewsIntegrationTest.java, server/sonar-views-bridge/pom.xml, server/sonar-views-bridge/src/main/java/org/sonar/server/views/ViewsBridge.java, sonar-core/src/main/java/org/sonar/core/platform/PluginClassloaderDef.java, sonar-core/src/main/java/org/sonar/core/platform/PluginClassloaderFactory.java, sonar-core/src/main/java/org/sonar/core/platform/PluginLoader.java, sonar-core/src/test/java/org/sonar/classloader/MaskReader.java, sonar-core/src/test/java/org/sonar/core/platform/PluginLoaderTest.java, sonar-db/src/main/java/org/sonar/db/component/ComponentDao.java, sonar-db/src/main/java/org/sonar/db/component/ComponentMapper.java, sonar-db/src/main/java/org/sonar/db/component/SnapshotQuery.java, sonar-db/src/main/resources/org/sonar/db/component/ComponentMapper.xml, sonar-db/src/main/resources/org/sonar/db/component/SnapshotMapper.xml, sonar-db/src/test/java/org/sonar/db/component/ComponentDaoTest.java, sonar-db/src/test/java/org/sonar/db/component/SnapshotDaoTest.java
this PR adds:
* the ability to run views the old way plugin were run: as part of the WebServer
* the ViewsBridge interface which is the entry point from the WebServer into Views
* some DAO changes to be able to run basic code from views
=> SONAR-6749 views in 5.2

sonar-db/src/main/java/org/sonar/db/component/ComponentDao.java, sonar-db/src/main/java/org/sonar/db/component/ComponentMapper.java, sonar-db/src/main/java/org/sonar/db/measure/custom/CustomMeasureDao.java, sonar-db/src/main/java/org/sonar/db/measure/custom/CustomMeasureDto.java, sonar-db/src/main/java/org/sonar/db/measure/custom/CustomMeasureMapper.java, sonar-db/src/main/resources/org/sonar/db/component/ComponentMapper.xml, sonar-db/src/main/resources/org/sonar/db/measure/custom/CustomMeasureMapper.xml, sonar-db/src/test/java/org/sonar/db/measure/custom/CustomMeasureDaoTest.java, sonar-db/src/test/resources/org/sonar/db/measure/custom/CustomMeasureDaoTest/select_by_metric_key_and_text_value.xml
SONAR-6749 Add query to get custom measures from a metric key and a text value
=> SONAR-6749 Add query to get custom measures from a metric key and a text value

server/sonar-server/src/main/java/org/sonar/server/computation/measure/Measure.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureComputersVisitor.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureDtoToMeasure.java, server/sonar-server/src/main/java/org/sonar/server/computation/measure/MeasureRepositoryImpl.java, server/sonar-server/src/test/java/org/sonar/server/component/ws/AppActionTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureComputersHolderRule.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureDtoToMeasureTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/ReportMeasureComputersVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/ViewsMeasureComputersVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/duplication/ws/ShowActionTest.java, sonar-db/src/main/java/org/sonar/db/measure/MeasureDto.java, sonar-db/src/main/resources/org/sonar/db/measure/MeasureMapper.xml, sonar-db/src/test/java/org/sonar/db/measure/MeasureDaoTest.java, sonar-db/src/test/java/org/sonar/db/measure/MeasureDtoTest.java, sonar-db/src/test/resources/org/sonar/db/measure/MeasureDaoTest/select_by_snapshot_and_metric_keys.xml, sonar-db/src/test/resources/org/sonar/db/measure/MeasureDaoTest/select_by_snapshot_and_metric_keys_with_characteristic_id.xml, sonar-db/src/test/resources/org/sonar/db/measure/MeasureDaoTest/select_by_snapshot_and_metric_keys_with_rule_id.xml, sonar-plugin-api/src/main/java/org/sonar/api/ce/measure/Component.java
- Allow measures from plugins to be computed by views
- Update Measure SQL query for Views to be able to return rule and characteristic measures
=> SONAR-6827 Update for Views

server/sonar-server/src/main/java/org/sonar/server/component/ComponentService.java, server/sonar-server/src/main/java/org/sonar/server/computation/component/ComponentImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/component/ReportAttributes.java, server/sonar-server/src/main/java/org/sonar/server/computation/component/UuidFactory.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/FillComponentsStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistComponentsStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/ValidateProjectStep.java, server/sonar-server/src/main/java/org/sonar/server/issue/IssueQueryService.java, server/sonar-server/src/main/java/org/sonar/server/test/ws/CoveredFilesAction.java, server/sonar-server/src/main/java/org/sonar/server/test/ws/ListAction.java, server/sonar-server/src/test/java/org/sonar/server/computation/component/ReportComponent.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistComponentsStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ReportPersistComponentsStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ViewsFillMeasuresWithVariationsStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ViewsPersistComponentsStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ViewsPersistSnapshotsStepTest.java, sonar-db/src/main/java/org/sonar/db/component/ComponentDtoFunctions.java, sonar-db/src/test/java/org/sonar/db/component/ComponentTesting.java
this PR contains changes in CE to implement Component persistence in Views
=> support for views component persistence

server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevelStartup.java, server/sonar-server/src/main/java/org/sonar/server/startup/DisplayLogOnDeprecatedProjects.java, server/sonar-server/src/test/java/org/sonar/server/startup/DisplayLogOnDeprecatedProjectsTest.java
SONAR-6548 Log a message on deprecated projects
=> SONAR-6548 Log a message on deprecated projects

server/sonar-server/src/main/java/org/sonar/server/qualitygate/RegisterQualityGates.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/RegisterQualityGatesTest.java
SONAR-6143 was incompletely implemented, my bad
=> SONAR-6143 update default QG to be fully based on water leak period

server/sonar-server/src/main/java/org/sonar/server/qualitygate/RegisterQualityGates.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/RegisterQualityGatesTest.java
SONAR-6143 'SonarQube way' quality gate should be set as default
=> SONAR-6143 'SonarQube way' quality gate should be set as default

server/sonar-server/src/main/java/org/sonar/server/computation/formula/FormulaExecutorComponentVisitor.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/SumFormula.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/VariationSumFormula.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/counter/IntSumCounter.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/counter/LongSumCounter.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/coverage/ElementsAndCoveredElementsCounter.java, server/sonar-server/src/main/java/org/sonar/server/computation/formula/coverage/ElementsAndCoveredElementsVariationCounter.java, server/sonar-server/src/test/java/org/sonar/server/computation/formula/IntSumFormulaTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/formula/LongSumFormulaTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/formula/ReportFormulaExecutorComponentVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/formula/ViewsFormulaExecutorComponentVisitorTest.java
required changes to SQ to fix project page for empty views
=> empty views support

server/sonar-web/src/main/webapp/WEB-INF/app/controllers/sessions_controller.rb
This fixes SSF-37 (no more details provided here).
This should be tested again, and we should make sure that there's no side effect. If everything's OK, this should be ported to 5.2 as mentioned in the related JIRA ticket.
=> SONAR-6880 Fix SSF-37

server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/CreateAction.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/CreateActionTest.java
See comment in CreationAction#guessMediaType()
=> Hack for IE - use mime type text/plain for api/qualityprofiles/create

server/sonar-server/src/main/java/org/sonar/server/computation/issue/IssueLifecycle.java, server/sonar-server/src/main/java/org/sonar/server/computation/issue/TrackerRawInputFactory.java, server/sonar-server/src/test/java/org/sonar/server/computation/issue/IssueLifecycleTest.java, sonar-core/src/main/java/org/sonar/core/issue/DefaultIssue.java, sonar-core/src/main/java/org/sonar/core/issue/IssueUpdater.java, sonar-core/src/test/java/org/sonar/core/issue/IssueUpdaterTest.java
SONAR-4865 Keep issue locations on existing issues
=> SONAR-4865 Keep issue locations on existing issues

server/sonar-server/src/main/java/org/sonar/server/computation/source/LastCommitVisitor.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/SendIssueNotificationsStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/source/LastCommitVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/SendIssueNotificationsStepTest.java
=> SONAR-6824 Use SCM Info repo

server/sonar-server/src/main/java/org/sonar/server/computation/step/SendIssueNotificationsStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/SendIssueNotificationsStepTest.java
SONAR-5794 Send notification step should not use batch repo to get project name
=> SONAR-5794 Send notification step should not use batch repo to get project name

server/sonar-server/src/main/java/org/sonar/server/test/index/TestResultSetIterator.java, server/sonar-server/src/test/java/org/sonar/server/test/index/TestIndexerTest.java, server/sonar-server/src/test/java/org/sonar/server/test/index/TestResultSetIteratorTest.java
SONAR-6414 Indexing tests should update updatedAt field
=> SONAR-6414 Indexing tests should update updatedAt field

sonar-core/src/main/resources/org/sonar/l10n/core.properties
SONAR-5876 Add l10n info for the metric
=> SONAR-5876 Add l10n info for the metric

server/sonar-server/src/main/java/org/sonar/server/computation/step/ComputeQProfileMeasureStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/QualityProfileEventsStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ComputeQProfileMeasureStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/QualityProfileEventsStepTest.java
SONAR-6729 CE not fail anymore when no quality profile found
=> SONAR-6729 CE not fail anymore when no quality profile found

sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/BatchReportReader.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/BatchReportWriter.java, sonar-batch-protocol/src/main/java/org/sonar/batch/protocol/output/FileStructure.java, sonar-batch-protocol/src/main/protobuf/batch_report.proto, sonar-batch-protocol/src/test/java/org/sonar/batch/protocol/output/BatchReportReaderTest.java, sonar-batch-protocol/src/test/java/org/sonar/batch/protocol/output/BatchReportWriterTest.java
SONAR-6988 Add cross project duplication info in batch report
Add duplication blocks
Add isCrossProjectDuplicationActivated boolen in metada
=> SONAR-6988 Add cross project duplication info in batch report

server/sonar-server/src/main/java/org/sonar/server/computation/duplication/IntegrateCrossProjectDuplications.java, server/sonar-server/src/test/java/org/sonar/server/computation/duplication/IntegrateCrossProjectDuplicationsTest.java
SONAR-6323 Duplications on current file are now ignored
=> SONAR-6323 Duplications on current file are now ignored

pom.xml, server/pom.xml, server/sonar-dev-cockpit-bridge/pom.xml, server/sonar-dev-cockpit-bridge/src/main/java/org/sonar/server/devcockpit/DevCockpitBridge.java, server/sonar-dev-cockpit-bridge/src/main/java/org/sonar/server/devcockpit/package-info.java, server/sonar-server/pom.xml, server/sonar-server/src/main/java/org/sonar/server/devcockpit/bridge/DevCockpitBootstrap.java, server/sonar-server/src/main/java/org/sonar/server/devcockpit/bridge/DevCockpitStopper.java, server/sonar-server/src/main/java/org/sonar/server/devcockpit/bridge/package-info.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/test/java/org/sonar/server/devcockpit/bridge/DevCockpitBootstrapTest.java, server/sonar-server/src/test/java/org/sonar/server/devcockpit/bridge/DevCockpitStopperTest.java
add Maven module sonar-dev-cockpit-bridge
=> SONAR-7027 add DevCockpitBridge and start/stop Dev Cockpit plugin

server/sonar-server/src/test/java/org/sonar/server/issue/ws/SearchActionComponentsMediumTest.java, sonar-db/src/main/java/org/sonar/db/user/AuthorDao.java, sonar-db/src/test/java/org/sonar/db/user/AuthorDaoTest.java
take session as parameter
use DbSession instead of SqlSession
remove unused methods
=> clean up AuthorDao

server/sonar-server/src/main/java/org/sonar/server/computation/step/AbstractComputationSteps.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/ReportComputationSteps.java
reduce duplication of code logic in implementations of ComputationSteps accross SQ and CE tasks in plugins
=> add AbstractComputationSteps

server/sonar-server/src/main/java/org/sonar/server/component/ComponentService.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/ApplyPermissionsStep.java, server/sonar-server/src/main/java/org/sonar/server/permission/PermissionService.java, server/sonar-server/src/test/java/org/sonar/server/component/ComponentServiceTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureRepositoryRule.java, sonar-db/src/main/java/org/sonar/db/permission/PermissionRepository.java, sonar-db/src/test/java/org/sonar/db/permission/PermissionRepositoryTest.java, sonar-db/src/test/resources/org/sonar/db/permission/PermissionRepositoryTest/apply_default_permission_template-result.xml, sonar-db/src/test/resources/org/sonar/db/permission/PermissionRepositoryTest/apply_default_permission_template.xml
Fix for https://github.com/SonarSource/sonar-dev-cockpit/pull/6
=> SONAR-7027 Fix for dev cockpit

sonar-db/src/main/resources/org/sonar/db/ce/CeQueueMapper.xml
Always select queue rows in the same order
=> Always select queue rows in the same order

server/sonar-server/src/main/java/org/sonar/server/computation/step/ComputeMeasureVariationsStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/measure/MeasureRepositoryRule.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ReportComputeMeasureVariationsStepTest.java
this fix bug on Dory where variations are no more computed for NCLOC, ...
=> do not try and compute variations of developer measures

it/it-tests/src/test/java/it/debt/DebtConfigurationRule.java, it/it-tests/src/test/java/it/debt/SqaleRatingMeasureTest.java, it/it-tests/src/test/java/it/debt/TechnicalDebtInIssueChangelogTest.java, it/it-tests/src/test/java/it/debt/TechnicalDebtTest.java, it/it-tests/src/test/java/it/debt/TechnicalDebtWidgetTest.java, sonar-core/src/main/java/org/sonar/core/config/DebtProperties.java, sonar-plugin-api/src/main/java/org/sonar/api/CoreProperties.java
SONAR-7028 Update default value of sonar.technicalDebt.ratingGrid
Default value is now "0.05,0.1,0.2,0.5", it was "0.1,0.2,0.5,1"
=> SONAR-7028 Update default value of sonar.technicalDebt.ratingGrid

server/sonar-server-benchmarks/src/test/java/org/sonar/server/benchmark/PersistFileSourcesStepTest.java, server/sonar-server/src/main/java/org/sonar/server/computation/duplication/DetailedTextBlock.java, server/sonar-server/src/main/java/org/sonar/server/computation/duplication/DuplicationRepository.java, server/sonar-server/src/main/java/org/sonar/server/computation/duplication/DuplicationRepositoryImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/duplication/IntegrateCrossProjectDuplications.java, server/sonar-server/src/main/java/org/sonar/server/computation/duplication/TextBlock.java, server/sonar-server/src/main/java/org/sonar/server/computation/source/DuplicationLineReader.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/DuplicationDataMeasuresStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/DuplicationMeasuresStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/LoadDuplicationsFromReportStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/duplication/DuplicationRepositoryImplTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/duplication/DuplicationRepositoryRule.java, server/sonar-server/src/test/java/org/sonar/server/computation/duplication/IntegrateCrossProjectDuplicationsTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/LoadDuplicationsFromReportStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/PersistFileSourcesStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ReportDuplicationMeasuresStepTest.java
improving duplication repository
* significantly reduce memory usage of the repo by storing the final, immutable, data
* support multiple identical original-duplicate paars sent by the batch
=> improving duplication repository

it/it-tests/src/test/java/it/serverSystem/RestartTest.java, it/it-tests/src/test/java/util/ItUtils.java, server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/FileSystem.java, server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/JavaProcessLauncher.java, server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/Monitor.java, server/sonar-process-monitor/src/test/java/org/sonar/process/monitor/MonitorTest.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/RestartAction.java, server/sonar-server/src/test/java/org/sonar/server/platform/ws/RestartActionTest.java, sonar-application/src/main/java/org/sonar/application/App.java, sonar-application/src/main/java/org/sonar/application/AppFileSystem.java, sonar-application/src/main/java/org/sonar/application/PropsBuilder.java, sonar-application/src/test/java/org/sonar/application/AppFileSystemTest.java, sonar-application/src/test/java/org/sonar/application/PropsBuilderTest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/HttpWsClient.java, sonar-ws/src/main/java/org/sonarqube/ws/client/WsClient.java, sonar-ws/src/main/java/org/sonarqube/ws/client/system/SystemService.java, sonar-ws/src/main/java/org/sonarqube/ws/client/system/package-info.java, sonar-ws/src/test/java/org/sonarqube/ws/client/system/SystemServiceTest.java
* fixes plugin not removed at restart
* some code improvements
=> improve restart WS

server/sonar-server/src/main/java/org/sonar/server/authentication/AuthenticationError.java, server/sonar-server/src/main/java/org/sonar/server/authentication/EmailAlreadyExistsException.java, server/sonar-server/src/main/java/org/sonar/server/authentication/InitFilter.java, server/sonar-server/src/main/java/org/sonar/server/authentication/OAuth2CallbackFilter.java, server/sonar-server/src/main/java/org/sonar/server/authentication/UserIdentityAuthenticator.java, server/sonar-server/src/test/java/org/sonar/server/authentication/InitFilterTest.java, server/sonar-server/src/test/java/org/sonar/server/authentication/UserIdentityAuthenticatorTest.java, server/sonar-web/src/main/webapp/WEB-INF/app/views/sessions/email_already_exists.erb, server/sonar-web/src/main/webapp/WEB-INF/lib/need_authentication.rb, sonar-core/src/main/java/org/sonar/core/config/CorePropertyDefinitions.java, sonar-core/src/test/java/org/sonar/core/config/CorePropertyDefinitionsTest.java, sonar-db/src/main/java/org/sonar/db/user/UserDao.java, sonar-db/src/main/java/org/sonar/db/user/UserMapper.java, sonar-db/src/main/resources/org/sonar/db/user/UserMapper.xml, sonar-db/src/test/java/org/sonar/db/user/UserDaoTest.java, sonar-db/src/test/resources/org/sonar/db/user/UserDaoTest/exists_by_email.xml, sonar-plugin-api/src/main/java/org/sonar/api/CoreProperties.java, sonar-plugin-api/src/main/java/org/sonar/api/server/authentication/BaseIdentityProvider.java, sonar-plugin-api/src/main/java/org/sonar/api/server/authentication/OAuth2IdentityProvider.java
SONAR-7217 Fail to authenticate user with existing email
=> SONAR-7217 Fail to authenticate user with existing email

server/sonar-web/src/main/webapp/WEB-INF/lib/need_authentication.rb, sonar-core/src/main/java/org/sonar/core/config/CorePropertyDefinitions.java, sonar-core/src/test/java/org/sonar/core/config/CorePropertyDefinitionsTest.java, sonar-plugin-api/src/main/java/org/sonar/api/CoreProperties.java
SONAR-7219 Remove sonar.security.updateUserAttributes property
=> SONAR-7219 Remove sonar.security.updateUserAttributes property

server/sonar-server/src/main/java/org/sonar/server/computation/step/LoadReportAnalysisMetadataHolderStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/LoadReportAnalysisMetadataHolderStepTest.java
failure implemented as early as possible
=> SONAR-7166 fail when projectKey in report is not the component key

server/sonar-server/src/main/java/org/sonar/server/computation/ws/TaskFormatter.java, server/sonar-server/src/test/java/org/sonar/server/computation/ws/TaskFormatterTest.java, sonar-db/src/main/java/org/sonar/db/DatabaseUtils.java, sonar-db/src/test/java/org/sonar/db/DatabaseUtilsTest.java, sonar-plugin-api/src/main/java/org/sonar/api/rule/RuleKey.java, sonar-plugin-api/src/test/java/org/sonar/api/rule/RuleKeyTest.java
This PR also includes some optimisations for `DatabaseUtils.executeLargeInputs`
=> SONAR-7168 don't query Components of CETasks 1 by 1 in TaskFormatter

server/sonar-server/src/main/java/org/sonar/server/computation/source/SymbolsLineReader.java
fix PersistFilesSources taking forever
=> SONAR-7257 make SymbolsLineReader instantaneous

server/sonar-server/src/main/java/org/sonar/server/computation/step/LoadReportAnalysisMetadataHolderStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/LoadReportAnalysisMetadataHolderStepTest.java
+ use `MessageException` instead of `IllegalStateException`
=> SONAR-7166 add explicit error when CeTask.componentKey is null

server/sonar-server/src/main/java/org/sonar/server/computation/issue/TrackerBaseInputFactory.java, server/sonar-server/src/main/java/org/sonar/server/computation/scm/ScmInfoRepositoryImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/QualityGateMeasuresStep.java
related to SONAR-6940 but since it's only partial implementation, the ticket won't be closed by added to the backlog
=> less access to file sources

server/sonar-server/src/main/java/org/sonar/server/computation/formula/AverageFormula.java, server/sonar-server/src/main/java/org/sonar/server/computation/step/ComplexityMeasuresStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/formula/AverageFormulaTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ReportComplexityMeasuresStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ViewsComplexityMeasuresStepTest.java
SONAR-7169 Remove fallback from AverageFormula
=> SONAR-7169 Remove fallback from AverageFormula

server/sonar-server/src/main/java/org/sonar/server/computation/scm/Changeset.java, server/sonar-server/src/main/java/org/sonar/server/computation/scm/ReportScmInfo.java, server/sonar-server/src/main/java/org/sonar/server/computation/scm/ScmInfoImpl.java, server/sonar-server/src/test/java/org/sonar/server/computation/scm/ReportScmInfoTest.java
SONAR-7114 Add line when changeset is invalid
=> SONAR-7114 Add line when changeset is invalid

server/sonar-process/src/main/java/org/sonar/process/ConfigurationUtils.java, server/sonar-process/src/main/java/org/sonar/process/FileUtils.java, server/sonar-process/src/main/java/org/sonar/process/MinimumViableSystem.java, server/sonar-process/src/test/java/org/sonar/process/FileUtilsTest.java, server/sonar-server/src/main/java/org/sonar/server/app/EmbeddedTomcat.java, server/sonar-server/src/main/java/org/sonar/server/app/TomcatContexts.java, server/sonar-server/src/main/java/org/sonar/server/computation/queue/report/ReportFiles.java, server/sonar-server/src/main/java/org/sonar/server/platform/DefaultServerFileSystem.java, server/sonar-server/src/main/java/org/sonar/server/platform/RailsAppsDeployer.java, server/sonar-server/src/main/java/org/sonar/server/plugins/PluginDownloader.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ServerPluginJarExploder.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ServerPluginRepository.java, server/sonar-server/src/main/java/org/sonar/server/qualityprofile/QProfileCopier.java, sonar-application/src/main/java/org/sonar/application/AppFileSystem.java, sonar-batch/src/main/java/org/sonar/batch/bootstrap/BatchPluginJarExploder.java, sonar-batch/src/main/java/org/sonar/batch/bootstrap/GlobalTempFolderProvider.java, sonar-batch/src/main/java/org/sonar/batch/cache/DefaultProjectCacheStatus.java, sonar-batch/src/main/java/org/sonar/batch/index/CachesManager.java, sonar-batch/src/main/java/org/sonar/batch/report/ReportPublisher.java, sonar-batch/src/main/java/org/sonar/batch/scan/MutableProjectReactorProvider.java, sonar-core/src/main/java/org/sonar/core/util/DefaultHttpDownloader.java, sonar-core/src/main/java/org/sonar/core/util/FileUtils.java, sonar-core/src/test/java/org/sonar/core/util/FileUtilsTest.java, sonar-plugin-api/src/main/java/org/sonar/api/utils/internal/DefaultTempFolder.java
fix it in App to avoid OOM if temp dir is big
fix it also in core, batch and server
=> SONAR-7125 fix temp dir cleaning

server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/Monitor.java
there is neither IT nor UT because I couldn't create any
=> SONAR-7384 ensure no thread can await its own termination in Monitor

server/sonar-server/src/main/java/org/sonar/server/qualityprofile/QProfileExporters.java, server/sonar-server/src/main/java/org/sonar/server/rule/RegisterRules.java, server/sonar-server/src/main/java/org/sonar/server/rule/ws/ActiveRuleCompleter.java, server/sonar-server/src/test/java/org/sonar/server/rule/RegisterRulesMediumTest.java, server/sonar-server/src/test/java/org/sonar/server/rule/RegisterRulesTest.java, sonar-db/src/main/java/org/sonar/db/qualityprofile/ActiveRuleDao.java, sonar-db/src/main/java/org/sonar/db/qualityprofile/ActiveRuleDtoFunctions.java, sonar-db/src/main/java/org/sonar/db/qualityprofile/ActiveRuleMapper.java, sonar-db/src/main/resources/org/sonar/db/qualityprofile/ActiveRuleMapper.xml, sonar-db/src/test/java/org/sonar/db/qualityprofile/ActiveRuleDaoTest.java, sonar-plugin-api/src/main/java/org/sonar/api/profiles/RulesProfile.java
SONAR-7330 When searching active rules by profile, ignore active rule on removed rules
=> SONAR-7330 When searching active rules by profile, ignore active rule on removed rules

sonar-core/src/main/java/org/sonar/core/config/DebtProperties.java, sonar-core/src/main/resources/org/sonar/l10n/core.properties
SONAR-7440 Remove SQALE word in widget/properties
=> SONAR-7440 Remove SQALE word in widget/properties

server/sonar-server/src/main/java/org/sonar/server/rule/RegisterRules.java, server/sonar-server/src/test/java/org/sonar/server/rule/RegisterRulesTest.java
SONAR-7479 Remove system tags from DB when no tags in plugin
=> SONAR-7479 Remove system tags from DB when no tags in plugin

it/it-plugins/base-auth-plugin/pom.xml, it/it-plugins/base-auth-plugin/src/main/java/FakeBaseIdProvider.java, it/it-tests/src/test/java/it/user/BaseIdentityProviderTest.java, it/it-tests/src/test/java/util/user/Groups.java, it/it-tests/src/test/java/util/user/UserRule.java, server/sonar-server/src/main/java/org/sonar/server/authentication/UserIdentityAuthenticator.java, server/sonar-server/src/main/java/org/sonar/server/usergroups/ws/UserGroupUpdater.java, server/sonar-server/src/test/java/org/sonar/server/authentication/UserIdentityAuthenticatorTest.java, sonar-db/src/main/java/org/sonar/db/user/GroupDao.java, sonar-db/src/main/resources/org/sonar/db/user/GroupMapper.xml, sonar-db/src/test/java/org/sonar/db/user/GroupDaoTest.java, sonar-plugin-api/src/main/java/org/sonar/api/server/authentication/UserIdentity.java, sonar-plugin-api/src/main/java/org/sonar/api/user/UserGroupValidation.java, sonar-plugin-api/src/test/java/org/sonar/api/server/authentication/UserIdentityTest.java, sonar-plugin-api/src/test/java/org/sonar/api/user/UserGroupValidationTest.java
SONAR-7448 Allow groups synchronization in IdentityProvider API
=> SONAR-7448 Allow groups synchronization in IdentityProvider API

it/it-tests/src/test/java/it/serverSystem/RestartTest.java, server/sonar-server/src/main/java/org/sonar/server/app/RestartFlagHolder.java, server/sonar-server/src/main/java/org/sonar/server/app/RestartFlagHolderImpl.java, server/sonar-server/src/main/java/org/sonar/server/platform/Platform.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel1.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/RestartAction.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/StatusAction.java, server/sonar-server/src/test/java/org/sonar/server/platform/ws/RestartActionTest.java, server/sonar-server/src/test/java/org/sonar/server/platform/ws/StatusActionTest.java, server/sonar-server/src/test/java/org/sonar/server/platform/ws/SystemWsTest.java
=> SONAR-7565 add RESTARTING status in /api/system/status

server/sonar-server/src/main/java/org/sonar/server/computation/step/PersistComponentsStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/ViewsPersistComponentsStepTest.java, sonar-db/src/test/java/org/sonar/db/component/ComponentDbTester.java
Update components copy resource id when persisting components in CE
=> Update components copy resource id when persisting components in CE

server/sonar-server/src/main/java/org/sonar/server/plugins/ws/PendingAction.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PendingActionTest.java, server/sonar-server/src/test/java/org/sonar/server/plugins/ws/PluginsWsMediumTest.java
SONAR-7269 Split installing plugins into installing and updating in api/plugins/pending
=> SONAR-7269 Split installing plugins into installing and updating in api/plugins/pending

sonar-plugin-api/src/main/java/org/sonar/api/batch/fs/InputFile.java
Method was added in SQ 5.1 in e9b5effe30cf68820a3dfb00bf736a325313206b
=> Add missing Javadoc

server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/BulkRuleActivationActions.java, server/sonar-server/src/main/java/org/sonar/server/rule/ws/RuleQueryFactory.java, server/sonar-server/src/main/java/org/sonar/server/rule/ws/SearchAction.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/QProfilesWsMediumTest.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/QProfilesWsTest.java, server/sonar-server/src/test/java/org/sonar/server/rule/index/RuleIndexTest.java, server/sonar-server/src/test/java/org/sonar/server/rule/ws/RuleQueryFactoryTest.java, server/sonar-server/src/test/resources/org/sonar/server/qualityprofile/ws/QProfilesWsMediumTest/bulk_activate_rule.json, server/sonar-server/src/test/resources/org/sonar/server/qualityprofile/ws/QProfilesWsMediumTest/bulk_activate_rule_not_all.json, server/sonar-server/src/test/resources/org/sonar/server/qualityprofile/ws/QProfilesWsMediumTest/does_not_return_warnings_when_bulk_activate_on_profile_and_rules_exist_on_another_language_than_profile.json, sonar-ws/src/main/java/org/sonarqube/ws/client/rule/RulesService.java, sonar-ws/src/test/java/org/sonarqube/ws/client/rule/RulesServiceTest.java
SONAR-6906 Filter rules on profile language when bulk active rules
=> SONAR-6906 Filter rules on profile language when bulk active rules

server/sonar-server/src/main/java/org/sonar/server/computation/step/QualityGateMeasuresStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/step/QualityGateMeasuresStepTest.java
they must have a different period
=> SONAR-7276 support multiple conditions for a given metric in QG

server/sonar-process/src/main/java/org/sonar/process/ProcessProperties.java, server/sonar-server/src/main/java/org/sonar/server/db/EmbeddedDatabase.java, server/sonar-server/src/test/java/org/sonar/server/db/EmbeddedDatabaseTest.java, sonar-application/src/main/java/org/sonar/application/JdbcSettings.java, sonar-application/src/test/java/org/sonar/application/JdbcSettingsTest.java
in addition, if sonar.jdbc.url is set, a warning will be logged
=> SONAR-7580 only sonar.embeddedDatabase.port required to set H2 port

server/sonar-server/src/main/java/org/sonar/server/qualitygate/QgateProjectFinder.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/SearchAction.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/QgateProjectFinderTest.java, sonar-db/src/main/java/org/sonar/db/qualitygate/ProjectQgateAssociationDao.java, sonar-db/src/main/java/org/sonar/db/qualitygate/ProjectQgateAssociationMapper.java, sonar-db/src/main/resources/org/sonar/db/qualitygate/ProjectQgateAssociationMapper.xml, sonar-db/src/test/java/org/sonar/db/qualitygate/ProjectQgateAssociationDaoTest.java
SONAR-7274 Return authorized projects in api/qualitygates/search
=> SONAR-7274 Return authorized projects in api/qualitygates/search

server/sonar-web/src/main/webapp/WEB-INF/app/views/project/history.html.erb
SONAR-6696 Fix profile description in history page
=> SONAR-6696 Fix profile description in history page

server/sonar-server/src/main/java/org/sonar/server/permission/ws/PermissionsWsModule.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/RemoveProjectCreatorFromTemplateAction.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/PermissionsWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/RemoveProjectCreatorFromTemplateActionTest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/permission/RemoveProjectCreatorFromTemplateWsRequest.java
review only the last commit about remove_project_creator_from_template
=> SONAR-7724 WS api/permissions/remove_project_creator_from_template

server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/AddProjectCreatorToTemplateAction.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/PermissionTemplateDtoToPermissionTemplateResponse.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/SearchTemplatesAction.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/SearchTemplatesData.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/SearchTemplatesDataLoader.java, server/sonar-server/src/main/resources/org/sonar/server/permission/ws/template/search_templates-example.json, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/DefaultPermissionTemplateFinderTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/PermissionTemplateDtoToPermissionTemplateResponseTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/SearchTemplatesActionTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/SearchTemplatesDataTest.java, sonar-db/src/main/java/org/sonar/db/permission/template/PermissionTemplateCharacteristicDao.java, sonar-db/src/main/resources/org/sonar/db/permission/template/PermissionTemplateCharacteristicMapper.xml, sonar-db/src/test/java/org/sonar/db/component/ResourceTypesRule.java, sonar-db/src/test/java/org/sonar/db/permission/template/PermissionTemplateCharacteristicDaoTest.java, sonar-db/src/test/java/org/sonar/db/permission/template/PermissionTemplateCharacteristicDtoTest.java, sonar-ws/src/main/protobuf/ws-permissions.proto
review only the last 2 commits about api/permissions/search_templates
=> SONAR-7726 WS api/permissions/search_templates returns with_project_creator metadata

server/sonar-server/src/main/java/org/sonar/server/permission/ws/DeleteTemplateAction.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/DeleteTemplateActionTest.java, sonar-db/src/main/java/org/sonar/db/permission/PermissionTemplateDao.java, sonar-db/src/main/java/org/sonar/db/permission/template/PermissionTemplateCharacteristicDao.java, sonar-db/src/main/java/org/sonar/db/permission/template/PermissionTemplateCharacteristicMapper.java, sonar-db/src/main/resources/org/sonar/db/permission/template/PermissionTemplateCharacteristicMapper.xml, sonar-db/src/test/java/org/sonar/db/permission/PermissionTemplateDaoTest.java, sonar-db/src/test/java/org/sonar/db/permission/template/PermissionTemplateCharacteristicDaoTest.java, sonar-db/src/test/resources/org/sonar/db/permission/PermissionTemplateDaoTest/deletePermissionTemplate-result.xml, sonar-db/src/test/resources/org/sonar/db/permission/PermissionTemplateDaoTest/deletePermissionTemplate.xml
SONAR-7746 Delete permission template characteristics when deleting a permission template
=> SONAR-7746 Delete permission template characteristics when deleting a permission template

sonar-plugin-api/src/main/java/org/sonar/api/scan/filesystem/PathResolver.java, sonar-plugin-api/src/test/java/org/sonar/api/scan/filesystem/PathResolverTest.java
=> SONAR-7788 Improve PathResolver::relativePath(File, File) when arguments

sonar-db/src/main/java/org/sonar/db/charset/MssqlCharsetHandler.java, sonar-db/src/test/java/org/sonar/db/charset/MssqlCharsetHandlerTest.java
collations can actually have a combination of case sensitivity and accent sensitivity
also, the might not end with accent sensitivity
=> SONAR-7798 mssql fix collation now support complex collations

server/sonar-server/src/main/java/org/sonar/server/authentication/JwtCsrfVerifier.java, server/sonar-server/src/main/java/org/sonar/server/authentication/JwtHttpHandler.java, server/sonar-server/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java, server/sonar-server/src/test/java/org/sonar/server/authentication/JwtCsrfVerifierTest.java, server/sonar-server/src/test/java/org/sonar/server/authentication/JwtHttpHandlerTest.java, server/sonar-server/src/test/java/org/sonar/server/authentication/UserSessionInitializerTest.java
SONAR-7732 Do not remove cookies when user is not authenticated
=> SONAR-7732 Do not remove cookies when user is not authenticated

server/sonar-server/src/main/java/org/sonar/server/computation/qualitymodel/NewQualityModelMeasuresVisitor.java, server/sonar-server/src/main/java/org/sonar/server/computation/qualitymodel/QualityModelMeasuresVisitor.java, server/sonar-server/src/test/java/org/sonar/server/computation/qualitymodel/NewQualityModelMeasuresVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/qualitymodel/QualityModelMeasuresVisitorForReportTest.java
SONAR-7870 Do not ignore unit tests when computing measures based on issues
=> SONAR-7870 Do not ignore unit tests when computing measures based on issues

server/sonar-server/src/main/resources/org/sonar/server/dashboard/widget/issue_filter.html.erb
This removes line, which was added accidentally in f661a14e2a03a44a9adfe18bb55f76754c9eabda.
=> SONAR-7945 Remove useless word in Issue widget

it/it-tests/src/test/java/it/Category4Suite.java, it/it-tests/src/test/java/it/serverSystem/LogsTest.java, server/sonar-server/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java, server/sonar-server/src/test/java/org/sonar/server/user/UserSessionFilterTest.java, sonar-application/src/main/assembly/conf/sonar.properties
SONAR-7581 ability to have user login in access.log
=> SONAR-7581 ability to have user login in access.log

sonar-application/src/main/assembly/conf/sonar.properties, sonar-db/src/main/java/org/sonar/db/DatabaseChecker.java
SONAR-7893 end of support of MSSQL 2008
=> SONAR-7893 end of support of MSSQL 2008

it/it-tests/src/test/java/it/settings/SettingsTest.java, server/sonar-server/src/main/java/org/sonar/server/settings/ws/ResetAction.java, server/sonar-server/src/main/java/org/sonar/server/settings/ws/SettingsWsModule.java, server/sonar-server/src/test/java/org/sonar/server/settings/ws/ResetActionTest.java, server/sonar-server/src/test/java/org/sonar/server/settings/ws/SettingsWsModuleTest.java, sonar-db/src/test/java/org/sonar/db/property/PropertyDbTester.java, sonar-ws/src/main/java/org/sonarqube/ws/client/setting/ResetRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/setting/SettingsService.java, sonar-ws/src/test/java/org/sonarqube/ws/client/setting/ResetRequestTest.java, sonar-ws/src/test/java/org/sonarqube/ws/client/setting/SettingsServiceTest.java
SONAR-7986 Create /api/settings/reset WS to remove the value of a setting
=> SONAR-7986 Create /api/settings/reset WS to remove the value of a setting

travis.sh
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sonarqube/zLhxT7PygVI/eq2G9U0KAgAJ
=> update PR analysis mode

sonar-core/src/main/resources/org/sonar/l10n/core.properties
We could talk more about the Leak Period, less about the dashboards.
=> Update UI welcome message

server/sonar-server/src/main/java/org/sonar/server/license/ws/LicensesWs.java, server/sonar-server/src/main/java/org/sonar/server/license/ws/LicensesWsModule.java, server/sonar-server/src/main/java/org/sonar/server/license/ws/ListAction.java, server/sonar-server/src/main/java/org/sonar/server/license/ws/package-info.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/resources/org/sonar/server/license/ws/list-example.json, server/sonar-server/src/test/java/org/sonar/server/license/ws/LicensesWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/license/ws/ListActionTest.java, server/sonar-server/src/test/java/org/sonar/server/setting/ws/ValuesActionTest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/license/LicensesService.java, sonar-ws/src/main/java/org/sonarqube/ws/client/license/LicensesWsParameters.java, sonar-ws/src/main/protobuf/ws-licenses.proto, sonar-ws/src/test/java/org/sonarqube/ws/client/license/LicensesServiceTest.java
SONAR-8039 Create /api/licenses/list to return licenses with metadata
=> SONAR-8039 Create /api/licenses/list to return licenses with metadata

it/it-tests/src/test/java/it/Category1Suite.java, it/it-tests/src/test/java/it/settings/EmailsTest.java, it/it-tests/src/test/java/util/ItUtils.java, server/sonar-server/src/main/java/org/sonar/server/email/ws/EmailsWs.java, server/sonar-server/src/main/java/org/sonar/server/email/ws/EmailsWsAction.java, server/sonar-server/src/main/java/org/sonar/server/email/ws/EmailsWsModule.java, server/sonar-server/src/main/java/org/sonar/server/email/ws/SendAction.java, server/sonar-server/src/main/java/org/sonar/server/email/ws/UpdateConfigurationAction.java, server/sonar-server/src/main/java/org/sonar/server/email/ws/package-info.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/test/java/org/sonar/server/email/ws/EmailsWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/email/ws/SendActionTest.java, server/sonar-server/src/test/java/org/sonar/server/email/ws/UpdateConfigurationActionTest.java
SONAR-8055 Create /api/emails/update WS to update email settings
=> SONAR-8055 Create /api/emails/update WS to update email settings

server/sonar-server/src/main/java/org/sonar/server/license/ws/ListAction.java, server/sonar-server/src/main/resources/org/sonar/server/license/ws/list-example.json, server/sonar-server/src/test/java/org/sonar/server/license/ws/ListActionTest.java, sonar-ws/src/main/protobuf/ws-licenses.proto
SONAR-8039 /api/licenses/list is returning license names
=> SONAR-8039 /api/licenses/list is returning license names

server/sonar-server/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java, server/sonar-server/src/main/java/org/sonar/server/platform/ServerIdGenerator.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/serverid/ws/ServerIdWs.java, server/sonar-server/src/main/java/org/sonar/server/serverid/ws/ServerIdWsAction.java, server/sonar-server/src/main/java/org/sonar/server/serverid/ws/ServerIdWsModule.java, server/sonar-server/src/main/java/org/sonar/server/serverid/ws/ShowAction.java, server/sonar-server/src/main/java/org/sonar/server/serverid/ws/package-info.java, server/sonar-server/src/main/resources/org/sonar/server/serverid/ws/show-example.json, server/sonar-server/src/test/java/org/sonar/server/authentication/UserSessionInitializerTest.java, server/sonar-server/src/test/java/org/sonar/server/serverid/ws/ServerIdWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/serverid/ws/ShowActionTest.java, sonar-ws/src/main/protobuf/ws-serverid.proto
SONAR-7985 Create /api/server_id/show WS
=> SONAR-7985 Create /api/server_id/show WS

it/it-plugins/property-sets-plugin/src/main/java/PropertySetsPlugin.java, it/it-plugins/server-plugin/src/main/java/ServerPlugin.java
Remove wrong property type in plugin IT
=> Remove wrong property type in plugin IT

it/it-plugins/server-plugin/src/main/java/ServerPlugin.java, it/it-tests/src/test/java/it/Category1Suite.java, it/it-tests/src/test/java/it/settings/DeprecatedPropertiesWsTest.java, it/it-tests/src/test/java/it/settings/SettingsTest.java, it/it-tests/src/test/java/util/ItUtils.java
SONAR-7970 SONAR-7986 Use new api/settings WS in ITs
=> SONAR-7970 SONAR-7986 Use new api/settings WS in ITs

it/it-tests/src/test/java/it/serverSystem/ServerSystemTest.java, server/sonar-server/src/main/java/org/sonar/server/serverid/ws/ShowAction.java, server/sonar-server/src/main/resources/org/sonar/server/serverid/ws/show-example.json, server/sonar-server/src/test/java/org/sonar/server/serverid/ws/ShowActionTest.java, server/sonar-web/src/main/js/apps/settings/serverId/ServerIdApp.js, sonar-ws/src/main/protobuf/ws-serverid.proto
=> correct wording

server/sonar-web/src/main/js/components/ui/Avatar.js
Fixed this one: https://jira.sonarsource.com/browse/SONAR-8033
=> SONAR-8033 Gravatar now works with non-lowercase email addresses.

server/sonar-server/src/main/java/org/sonar/server/ui/JRubyFacade.java, sonar-plugin-api/src/main/java/org/sonar/api/config/Settings.java
Remove unused methods about settings in JRubyFacade
=> Remove unused methods about settings in JRubyFacade

sonar-plugin-api/src/main/java/org/sonar/api/profiles/ProfileExporter.java, sonar-plugin-api/src/main/java/org/sonar/api/profiles/ProfileImporter.java
SONAR-6407 Missing javadoc on profileImporter and profileExporter
=> SONAR-6407 Missing javadoc on profileImporter and profileExporter

server/sonar-server/src/main/java/org/sonar/server/issue/IssueQueryService.java, server/sonar-server/src/main/java/org/sonar/server/issue/workflow/State.java, server/sonar-server/src/main/java/org/sonar/server/usergroups/ws/DeleteAction.java, server/sonar-server/src/test/java/org/sonar/server/issue/workflow/StateTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/ws/SearchActionMediumTest.java, server/sonar-server/src/test/java/org/sonar/server/usergroups/ws/DeleteActionTest.java
- Http error 400 is sent when trying an incorrect issue transition
- Validate a 400 is sent when WS issues/search cannot parse the date
- revent deletion of the last admin group when no standalone admin user
=> Wednesday Hardening!

it/it-tests/src/test/java/it/user/BaseIdentityProviderTest.java, it/it-tests/src/test/java/it/user/LocalAuthenticationTest.java, it/it-tests/src/test/java/it/user/RealmAuthenticationTest.java, sonar-plugin-api/src/main/java/org/sonar/api/server/authentication/UserIdentity.java, sonar-plugin-api/src/test/java/org/sonar/api/server/authentication/UserIdentityTest.java
SONAR-8031 Allow user login with 2 characters in Realm and IdentityProvider API
=> SONAR-8031 Allow user login with 2 characters in Realm and IdentityProvider API

server/sonar-server/src/main/java/org/sonar/server/measure/ws/ComponentDtoToWsComponent.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/MeasureDtoToWsMeasure.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/MeasuresWsModule.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/MetricDtoWithBestValue.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/SnapshotDtoToWsPeriods.java, server/sonar-server/src/main/java/org/sonar/server/ws/KeyExamples.java, server/sonar-server/src/main/resources/org/sonar/server/measure/ws/search-example.json, server/sonar-server/src/test/java/org/sonar/server/measure/ws/MeasuresWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/measure/ws/SearchActionTest.java, sonar-db/src/main/java/org/sonar/db/component/SnapshotDao.java, sonar-db/src/test/java/org/sonar/db/component/ComponentTesting.java, sonar-ws/src/main/java/org/sonarqube/ws/client/measure/SearchRequest.java, sonar-ws/src/main/protobuf/ws-measures.proto, sonar-ws/src/test/java/org/sonarqube/ws/client/measure/SearchRequestTest.java
Not included for the time being
- no permission check (dependency on Atlas work on organization)
- ~~no best value added~~
- ~~lack of tests on the request checks~~
- no reference uuid/key (outside the scope of my sprint)
=> SONAR-8120 Create WS measures/search to search for measures

server/sonar-ce/src/main/java/org/sonar/ce/container/ComputeEngineContainerImpl.java, server/sonar-ce/src/test/java/org/sonar/ce/container/ComputeEngineContainerImplTest.java, server/sonar-server/src/main/java/org/sonar/server/component/ComponentCleanerService.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/step/IndexProjectMeasuresStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/step/ReportComputationSteps.java, server/sonar-server/src/main/java/org/sonar/server/project/es/ProjectMeasuresIndexer.java, server/sonar-server/src/main/java/org/sonar/server/project/es/ProjectMeasuresResultSetIterator.java, server/sonar-server/src/test/java/org/sonar/server/component/ComponentCleanerServiceTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/IndexProjectMeasuresStepTest.java, server/sonar-server/src/test/java/org/sonar/server/project/es/ProjectMeasuresIndexerTest.java, server/sonar-server/src/test/java/org/sonar/server/project/es/ProjectMeasuresResultSetIteratorTest.java, server/sonar-server/src/test/java/org/sonar/server/project/ws/BulkDeleteActionTest.java, server/sonar-server/src/test/java/org/sonar/server/project/ws/DeleteActionTest.java
SONAR-8222 Update project measures index at the end of each project analysis
SONAR-8229 Update project measures index when removing a project
=> Update project measures index

.cix.yml
=> Re-enable upgrade tests

server/sonar-server/src/main/java/org/sonar/server/measure/ws/ComponentDtoToWsComponent.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/MeasureDtoToWsMeasure.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/SearchAction.java, server/sonar-server/src/main/resources/org/sonar/server/measure/ws/search-example.json, server/sonar-server/src/test/java/org/sonar/server/measure/ws/SearchActionTest.java, server/sonar-web/src/main/js/apps/projects/store/actions.js, sonar-db/src/test/java/org/sonar/db/component/ComponentTesting.java, sonar-ws/src/main/java/org/sonarqube/ws/client/measure/MeasuresWsParameters.java, sonar-ws/src/main/java/org/sonarqube/ws/client/measure/SearchRequest.java, sonar-ws/src/main/protobuf/ws-measures.proto, sonar-ws/src/test/java/org/sonarqube/ws/client/measure/SearchRequestTest.java
SONAR-8120 Remove componentIds parameter
=> SONAR-8120 Remove componentIds parameter

server/sonar-server/src/main/java/org/sonar/server/component/ws/AppAction.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/step/CoverageMeasuresStep.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/step/NewCoverageMeasuresStep.java, server/sonar-server/src/test/java/org/sonar/server/component/ws/AppActionTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/formula/ReportFormulaExecutorComponentVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/formula/ViewsFormulaExecutorComponentVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/ReportCoverageMeasuresStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/ReportNewCoverageMeasuresStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/ViewsCoverageMeasuresStepTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/ViewsNewCoverageMeasuresStepTest.java, sonar-db/src/main/java/org/sonar/db/version/v62/UpdateQualityGateConditionsOnCoverage.java
SONAR-8282 Clean up code related to removal of IT/overall coverage
=> SONAR-8282 Clean up code related to removal of IT/overall coverage

server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/issue/commonrule/BranchCoverageRule.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/issue/commonrule/LineCoverageRule.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/issue/commonrule/BranchCoverageRuleTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/issue/commonrule/LineCoverageRuleTest.java
SONAR-8282 Fix issue message on branch coverage common rule
=> SONAR-8282 Fix issue message on branch coverage common rule

it/it-tests/src/test/java/it/Category5Suite.java, it/it-tests/src/test/java/it/user/BaseIdentityProviderTest.java, it/it-tests/src/test/java/it/user/SsoAuthenticationTest.java, server/sonar-server/src/main/java/org/sonar/server/authentication/AuthenticationModule.java, server/sonar-server/src/main/java/org/sonar/server/authentication/JwtHttpHandler.java, server/sonar-server/src/main/java/org/sonar/server/authentication/SsoAuthenticator.java, server/sonar-server/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java, server/sonar-server/src/test/java/org/sonar/server/authentication/SsoAuthenticatorTest.java, server/sonar-server/src/test/java/org/sonar/server/authentication/UserSessionInitializerTest.java, sonar-application/src/main/assembly/conf/sonar.properties
SONAR-5430 User authentication by HTTP header
=> SONAR-5430 User authentication by HTTP header

server/sonar-server/src/main/java/org/sonar/server/authentication/SsoAuthenticator.java, server/sonar-server/src/test/java/org/sonar/server/authentication/SsoAuthenticatorTest.java
SONAR-5430 Load SSO settings only at startup
=> SONAR-5430 Load SSO settings only at startup

server/sonar-server/src/main/java/org/sonar/server/measure/ws/ComponentTreeDataLoader.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/project/ws/SearchMyProjectsDataLoader.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/ProjectStatusAction.java, server/sonar-server/src/main/resources/org/sonar/server/measure/ws/search-example.json, server/sonar-server/src/test/java/org/sonar/server/measure/ws/SearchActionTest.java, server/sonar-web/src/main/js/api/measures.js, server/sonar-web/src/main/js/apps/projects/store/actions.js, sonar-db/src/main/java/org/sonar/db/DatabaseUtils.java, sonar-db/src/main/java/org/sonar/db/measure/MeasureDao.java, sonar-db/src/main/java/org/sonar/db/measure/MeasureMapper.java, sonar-db/src/main/java/org/sonar/db/measure/MeasureQuery.java, sonar-db/src/main/java/org/sonar/db/permission/AuthorizationDao.java, sonar-db/src/main/java/org/sonar/db/permission/AuthorizationMapper.java, sonar-db/src/main/resources/org/sonar/db/measure/MeasureMapper.xml, sonar-db/src/test/java/org/sonar/db/measure/MeasureDaoTest.java, sonar-db/src/test/java/org/sonar/db/measure/MeasureQueryTest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/measure/MeasuresWsParameters.java, sonar-ws/src/main/java/org/sonarqube/ws/client/measure/SearchRequest.java, sonar-ws/src/test/java/org/sonarqube/ws/client/measure/SearchRequestTest.java
As this WS is only querying projects, it's useless to allow searching on any components 
=> It allow to improve performance by directly querying SNAPSHOTS.CoMPONENT_UUID with given project uuids without any join on projects
=> SONAR-8325 Improve performance of api/measures/search

server/sonar-web/src/main/js/apps/component-issues/app.js, server/sonar-web/src/main/js/apps/issues/HeaderView.js, server/sonar-web/src/main/js/apps/issues/app.js, server/sonar-web/src/main/js/apps/issues/controller.js, server/sonar-web/src/main/js/apps/issues/facets/assignee-facet.js, server/sonar-web/src/main/js/apps/issues/facets/mode-facet.js, server/sonar-web/src/main/js/apps/issues/layout.js, server/sonar-web/src/main/js/apps/issues/styles.css, server/sonar-web/src/main/js/apps/issues/templates/facets/issues-assignee-facet.hbs, server/sonar-web/src/main/js/apps/issues/templates/facets/issues-mode-facet.hbs, server/sonar-web/src/main/js/apps/issues/templates/facets/issues-my-issues-facet.hbs, server/sonar-web/src/main/js/apps/issues/templates/issues-layout.hbs, server/sonar-web/src/main/js/apps/issues/templates/issues-workspace-header.hbs, server/sonar-web/src/main/js/main/nav/global/global-nav-menu.js, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> SONAR-8374 Make the "Me" option more visible on the "Issues" page

server/sonar-server/src/main/java/org/sonar/server/es/SearchOptions.java, server/sonar-server/src/main/java/org/sonar/server/issue/IssueQuery.java, server/sonar-server/src/main/java/org/sonar/server/issue/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ActiveRuleChange.java, server/sonar-server/src/main/java/org/sonar/server/qualityprofile/RuleActivator.java, server/sonar-server/src/test/java/org/sonar/server/es/SearchOptionsTest.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ActiveRuleChangeTest.java, sonar-db/src/test/java/org/sonar/db/qualityprofile/QProfileChangeDaoTest.java
- SONAR-8005 Limit ES results to the first 10'000
=> Hardening Teryk - Monday

it/it-tests/src/test/java/it/serverSystem/LogsTest.java, server/sonar-ce/src/main/java/org/sonar/ce/container/ComputeEngineContainerImpl.java, server/sonar-ce/src/test/java/org/sonar/ce/container/ComputeEngineContainerImplTest.java, server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/Monitor.java, server/sonar-process/src/main/java/org/sonar/process/Lifecycle.java, server/sonar-process/src/main/java/org/sonar/process/LogbackHelper.java, server/sonar-process/src/test/java/org/sonar/process/LifecycleTest.java, server/sonar-search/src/main/java/org/sonar/search/SearchLogging.java, server/sonar-search/src/test/java/org/sonar/search/SearchLoggingTest.java, server/sonar-server/src/main/java/org/sonar/ce/log/CeProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/app/ServerProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/app/WebServerProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel1.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/ChangeLogLevelAction.java, server/sonar-server/src/test/java/org/sonar/ce/log/CeProcessLoggingTest.java, server/sonar-server/src/test/java/org/sonar/server/app/WebServerProcessLoggingTest.java, sonar-application/src/main/assembly/conf/sonar.properties, sonar-application/src/main/java/org/sonar/application/App.java, sonar-application/src/main/java/org/sonar/application/AppLogging.java, sonar-application/src/test/java/org/sonar/application/AppLoggingTest.java, sonar-db/pom.xml, sonar-db/src/main/java/org/sonar/db/DefaultDatabase.java, sonar-db/src/test/java/org/sonar/db/DefaultDatabaseTest.java, sonar-db/src/test/java/org/sonar/db/TestDb.java
=> SONAR-8336 add properties to control sql logs

it/it-tests/src/test/java/it/serverSystem/LogsTest.java, server/sonar-ce/src/main/java/org/sonar/ce/container/ComputeEngineContainerImpl.java, server/sonar-ce/src/test/java/org/sonar/ce/container/ComputeEngineContainerImplTest.java, server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/Monitor.java, server/sonar-process/src/main/java/org/sonar/process/Lifecycle.java, server/sonar-process/src/main/java/org/sonar/process/LogbackHelper.java, server/sonar-process/src/test/java/org/sonar/process/LifecycleTest.java, server/sonar-search/src/main/java/org/sonar/search/SearchLogging.java, server/sonar-search/src/test/java/org/sonar/search/SearchLoggingTest.java, server/sonar-server/src/main/java/org/sonar/ce/log/CeProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/app/ServerProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/app/WebServerProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel1.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/ChangeLogLevelAction.java, server/sonar-server/src/test/java/org/sonar/ce/log/CeProcessLoggingTest.java, server/sonar-server/src/test/java/org/sonar/server/app/WebServerProcessLoggingTest.java, sonar-application/src/main/assembly/conf/sonar.properties, sonar-application/src/main/java/org/sonar/application/App.java, sonar-application/src/main/java/org/sonar/application/AppLogging.java, sonar-application/src/test/java/org/sonar/application/AppLoggingTest.java, sonar-db/pom.xml, sonar-db/src/main/java/org/sonar/db/DefaultDatabase.java, sonar-db/src/test/java/org/sonar/db/DefaultDatabaseTest.java, sonar-db/src/test/java/org/sonar/db/TestDb.java
=> SONAR-8337 add propertes for es logs

it/it-tests/src/test/java/it/serverSystem/LogsTest.java, server/sonar-ce/src/main/java/org/sonar/ce/container/ComputeEngineContainerImpl.java, server/sonar-ce/src/test/java/org/sonar/ce/container/ComputeEngineContainerImplTest.java, server/sonar-process-monitor/src/main/java/org/sonar/process/monitor/Monitor.java, server/sonar-process/src/main/java/org/sonar/process/Lifecycle.java, server/sonar-process/src/main/java/org/sonar/process/LogbackHelper.java, server/sonar-process/src/test/java/org/sonar/process/LifecycleTest.java, server/sonar-search/src/main/java/org/sonar/search/SearchLogging.java, server/sonar-search/src/test/java/org/sonar/search/SearchLoggingTest.java, server/sonar-server/src/main/java/org/sonar/ce/log/CeProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/app/ServerProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/app/WebServerProcessLogging.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel1.java, server/sonar-server/src/main/java/org/sonar/server/platform/ws/ChangeLogLevelAction.java, server/sonar-server/src/test/java/org/sonar/ce/log/CeProcessLoggingTest.java, server/sonar-server/src/test/java/org/sonar/server/app/WebServerProcessLoggingTest.java, sonar-application/src/main/assembly/conf/sonar.properties, sonar-application/src/main/java/org/sonar/application/App.java, sonar-application/src/main/java/org/sonar/application/AppLogging.java, sonar-application/src/test/java/org/sonar/application/AppLoggingTest.java, sonar-db/pom.xml, sonar-db/src/main/java/org/sonar/db/DefaultDatabase.java, sonar-db/src/test/java/org/sonar/db/DefaultDatabaseTest.java, sonar-db/src/test/java/org/sonar/db/TestDb.java
=> SONAR-8338 add properties to control log level of JMX related loggers

sonar-db/src/main/java/org/sonar/db/version/v60/PopulateUuidPathColumnOnProjects.java, sonar-db/src/test/java/org/sonar/db/version/v60/PopulateUuidPathColumnOnProjectsTest.java
https://jira.sonarsource.com/browse/SONAR-8391
=> SONAR-8391 fix NPE when SNAPSHOTS.PATH has an invalid ID

server/sonar-server/src/main/java/org/sonar/server/issue/notification/IssueChangeNotification.java, server/sonar-server/src/main/java/org/sonar/server/issue/notification/IssueChangesEmailTemplate.java, server/sonar-server/src/test/java/org/sonar/server/issue/notification/IssueChangesEmailTemplateTest.java, server/sonar-server/src/test/resources/org/sonar/server/issue/notification/IssueChangesEmailTemplateTest/email_should_display_resolution_change.txt, server/sonar-server/src/test/resources/org/sonar/server/issue/notification/IssueChangesEmailTemplateTest/email_with_action_plan_change.txt, server/sonar-server/src/test/resources/org/sonar/server/issue/notification/IssueChangesEmailTemplateTest/email_with_assignee_change.txt, server/sonar-server/src/test/resources/org/sonar/server/issue/notification/IssueChangesEmailTemplateTest/email_with_multiple_changes.txt
This reverts commit 5e09c80b98511948c5c261181deaab035f627bc6.
=> Revert "SONAR-6996 Replace the issue key by the file name in the 'issue changed' notification"

it/it-tests/src/test/java/it/Category3Suite.java, it/it-tests/src/test/java/it/organization/OrganizationIt.java, it/it-tests/src/test/java/it/serverSystem/RestartTest.java, it/it-tests/src/test/java/it/updateCenter/UpdateCenterTest.java, server/sonar-ce/src/test/java/org/sonar/ce/container/ComputeEngineContainerImplTest.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, sonar-core/src/main/java/org/sonar/core/config/CorePropertyDefinitions.java, sonar-core/src/test/java/org/sonar/core/config/CorePropertyDefinitionsTest.java
This reverts commit 55fefdf810b8326b803ad8b7ce4f0c047fc57ef1.
=> restore ROOT WS disabled for 6.2 release

server/sonar-web/src/main/js/api/components.js, server/sonar-web/src/main/js/api/favorites.js, server/sonar-web/src/main/js/app/components/nav/global/SearchView.js
=> refactor SearchView to remove $ and _ dependencies

sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/DefaultSensorStorage.java, sonar-scanner-engine/src/test/java/org/sonar/scanner/mediumtest/measures/MeasuresMediumTest.java
=> SONAR-8540 Fix saving of raw IT/Overall coverage measures

it/it-tests/src/test/java/it/dbCleaner/PurgeTest.java, server/sonar-web/src/main/webapp/WEB-INF/db/migrate/1154_clean_usurper_root_components.rb
SONAR-8580 add temporary index in DB migration CleanUsurperRootComponents
=> SONAR-8580 add temporary index in DB migration CleanUsurperRootComponents

pom.xml, server/sonar-server/pom.xml, server/sonar-server/src/main/java/org/sonar/server/app/TomcatConnectors.java, server/sonar-server/src/main/java/org/sonar/server/app/TomcatContexts.java, server/sonar-server/src/test/java/org/sonar/server/app/TomcatConnectorsTest.java
SONAR-8545 Upgrade Apache Tomcat from 8.0 to 8.5
=> SONAR-8545 Upgrade Apache Tomcat from 8.0 to 8.5

server/sonar-db-migration/src/main/java/org/sonar/server/platform/db/migration/charset/OracleCharsetHandler.java, server/sonar-db-migration/src/test/java/org/sonar/server/platform/db/migration/charset/OracleCharsetHandlerTest.java, sonar-db/src/main/java/org/sonar/db/dialect/Oracle.java, sonar-db/src/test/java/org/sonar/db/dialect/OracleTest.java
Experiment to set Oracle NLS_SORT in sessions
=> SONAR-8585 Do not require parameter NLS_SORT=BINARY on Oracle database

sonar-db/src/main/java/org/sonar/db/version/v564/CleanUsurperRootComponents.java, sonar-db/src/test/java/org/sonar/db/version/v564/CleanUsurperRootComponentsTest.java
SONAR-8642 fix MSSQL collation in CleanUsurperRootComponents
=> SONAR-8642 fix MSSQL collation in CleanUsurperRootComponents

server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/TemplateGroupsAction.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/AddGroupToTemplateActionTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/RemoveGroupFromTemplateActionTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/template/TemplateGroupsActionTest.java, sonar-db/src/main/java/org/sonar/db/permission/template/PermissionTemplateDao.java, sonar-db/src/main/java/org/sonar/db/permission/template/PermissionTemplateMapper.java, sonar-db/src/main/resources/org/sonar/db/permission/template/PermissionTemplateMapper.xml, sonar-db/src/test/java/org/sonar/db/permission/template/GroupWithPermissionTemplateDaoTest.java
and a given group name exists in multiple organizations
=> SONAR-8682 fix error when filtering on name

it/it-tests/src/test/java/it/Category3Suite.java, it/it-tests/src/test/java/it/analysis/PermissionTest.java, it/it-tests/src/test/java/it/settings/DeprecatedPropertiesWsTest.java, server/sonar-server/src/main/java/org/sonar/server/property/ws/IndexAction.java, server/sonar-server/src/main/java/org/sonar/server/setting/ws/SettingsPermissionPredicates.java, server/sonar-server/src/main/java/org/sonar/server/ws/DeprecatedRestWebServiceFilter.java, server/sonar-server/src/test/java/org/sonar/server/property/ws/IndexActionTest.java, server/sonar-server/src/test/java/org/sonar/server/setting/ws/ValuesActionTest.java, server/sonar-server/src/test/java/org/sonar/server/ws/DeprecatedRestWebServiceFilterTest.java
Key parameter was badly used instead of id when rewritting api/properties to Java
=> SONAR-7300 Replace key parameter by id

server/sonar-server/src/main/java/org/sonar/server/permission/ws/UsersAction.java, server/sonar-server/src/main/java/org/sonar/server/usergroups/ws/UsersAction.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/UsersActionTest.java, server/sonar-server/src/test/java/org/sonar/server/usergroups/ws/UsersActionTest.java, server/sonar-server/src/test/resources/org/sonar/server/usergroups/ws/UsersActionTest/all.json, server/sonar-server/src/test/resources/org/sonar/server/usergroups/ws/UsersActionTest/all_ada.json, sonar-db/src/main/java/org/sonar/db/permission/PermissionQuery.java, sonar-db/src/main/java/org/sonar/db/user/UserMembershipQuery.java, sonar-db/src/main/resources/org/sonar/db/permission/GroupPermissionMapper.xml, sonar-db/src/main/resources/org/sonar/db/permission/UserPermissionMapper.xml, sonar-db/src/main/resources/org/sonar/db/permission/template/PermissionTemplateMapper.xml, sonar-db/src/main/resources/org/sonar/db/user/GroupMembershipMapper.xml, sonar-db/src/test/java/org/sonar/db/permission/UserPermissionDaoTest.java, sonar-db/src/test/java/org/sonar/db/user/GroupMembershipDaoTest.java, sonar-db/src/test/resources/org/sonar/db/user/GroupMembershipDaoTest/shared_plus_empty_group.xml
- only search on name is case insensitive
- I still have to do a local performance test to check it scales for 10'000 users
=> Search on Users case insensitive

server/sonar-server/src/main/java/org/sonar/server/app/TomcatContexts.java, sonar-application/src/main/assembly/conf/sonar.properties
SONAR-8703 Remove internal setting "sonar.web.dev.sources"
=> SONAR-8703 Remove internal setting "sonar.web.dev.sources"

server/sonar-server/src/main/java/org/sonar/server/organization/OrganizationCreation.java, server/sonar-server/src/main/java/org/sonar/server/organization/OrganizationCreationImpl.java, server/sonar-server/src/test/java/org/sonar/server/organization/OrganizationCreationImplTest.java, sonar-db/src/test/java/org/sonar/db/user/UserDbTester.java
=> SONAR-8752 SONAR-8751 personal org name from username

server/sonar-web/src/main/js/apps/projects/filters/Filter.js, server/sonar-web/src/main/js/apps/projects/filters/LanguageFilter.js, server/sonar-web/src/main/js/apps/projects/filters/LanguageFilterFooter.js, server/sonar-web/src/main/less/components/search-navigator.less
@julienlancelot We will be able to verify if it really work when the api is updated to return languages that are in the filter but not top 6.
=> SONAR-8876 Language facet searchbox on projects page

server/sonar-ce/src/main/java/org/sonar/ce/app/CeServer.java, sonar-core/src/main/java/org/sonar/core/platform/ComponentContainer.java
* fix support for `MessageException` in `CeServer`
* fix thread leak when web fails to start
=> SONAR-7485 and SONAR-7500

server/sonar-db-dao/src/main/java/org/sonar/db/user/UserDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/user/UserMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/user/UserMapper.xml, server/sonar-db-dao/src/test/java/org/sonar/db/organization/OrganizationDbTester.java, server/sonar-db-dao/src/test/java/org/sonar/db/user/UserDaoTest.java, server/sonar-server/src/main/java/org/sonar/server/organization/OrganizationCreationImpl.java, server/sonar-server/src/main/java/org/sonar/server/user/UserUpdater.java, server/sonar-server/src/main/java/org/sonar/server/user/ws/CreateAction.java, server/sonar-server/src/test/java/org/sonar/server/organization/OrganizationCreationImplTest.java, server/sonar-server/src/test/java/org/sonar/server/user/UserUpdaterTest.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/ChangePasswordActionTest.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/CreateActionTest.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/DeactivateActionTest.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/UsersWsTest.java
- SONAR-8901 Associate new users to organizations
- SONAR-8930 When removing a user, remove him from any organization he belongs to
=> Handle membership when creating/removing user

server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/DeleteAction.java, server/sonar-server/src/main/java/org/sonar/server/qualityprofile/ws/QProfileWsSupport.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/DeleteActionTest.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/QProfileWsSupportTest.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/ws/QProfilesWsTest.java
=> SONAR-8857 make ws/qualityprofiles/delete organization aware

sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/filesystem/InputFileBuilder.java
* Just some typos that I've noticed in the CLI warning msgs.
=> Typos fix in the file warning msgs.

server/sonar-web/src/main/js/apps/overview/meta/Meta.js, server/sonar-web/src/main/js/apps/overview/meta/MetaTags.js, server/sonar-web/src/main/js/apps/overview/meta/__tests__/MetaTags-test.js, server/sonar-web/src/main/js/apps/overview/meta/__tests__/__snapshots__/MetaTags-test.js.snap, server/sonar-web/src/main/js/apps/projects/components/ProjectTagsSelectorContainer.js, server/sonar-web/src/main/js/components/common/MultiSelect.js, server/sonar-web/src/main/js/components/tags/TagsList.css, server/sonar-web/src/main/js/components/tags/TagsSelector.js, server/sonar-web/src/main/js/components/tags/__tests__/__snapshots__/TagsSelector-test.js.snap, server/sonar-web/src/main/less/components/menu.less
* Limit list size to 10 elements max
* Fix long tags display
=> SONAR-8844 Fix project tags selector

server/sonar-server/src/main/java/org/sonar/server/component/ws/SearchProjectsAction.java, server/sonar-server/src/main/java/org/sonar/server/projecttag/ws/SetAction.java, server/sonar-server/src/test/java/org/sonar/server/projecttag/ws/SetActionTest.java
* restrict tag to project only
* typo in api/components/search_projects description
=> Small fixes relating to project tags

server/sonar-web/src/main/js/apps/projects/filters/SearchFilter.js, server/sonar-web/src/main/js/apps/projects/filters/__tests__/__snapshots__/SearchFilter-test.js.snap
This reverts commit 98ee1ae87253fb17f8f96b24454be351cdeef001.
=> Revert "Add autofocus in project search on projects page"

server/sonar-server/src/main/java/org/sonar/server/organization/OrganizationFlags.java, server/sonar-server/src/main/java/org/sonar/server/organization/OrganizationFlagsImpl.java, server/sonar-server/src/main/java/org/sonar/server/rule/ws/CreateAction.java, server/sonar-server/src/test/java/org/sonar/server/organization/TestOrganizationFlags.java
🌊  This PR is based on #1907, which should be reviewed first.
=> SONAR-9115 let api/rules/create fail, if organizations are enabled

server/sonar-server/src/test/java/org/sonar/server/util/OkHttpClientProviderTest.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/ScannerWsClientProvider.java, sonar-ws/src/main/java/org/sonarqube/ws/client/OkHttpClientBuilder.java, sonar-ws/src/test/java/org/sonarqube/ws/client/HttpConnectorTest.java, sonar-ws/src/test/java/org/sonarqube/ws/client/OkHttpClientBuilderTest.java
Will be tested by an IT in SQ Scanner API:
https://github.com/SonarSource/sonar-scanner-api/pull/43
=> SONAR-9155 Fix HTTPS proxy authentication

it/it-tests/src/test/java/it/authorisation/ExecuteAnalysisPermissionTest.java, it/it-tests/src/test/java/it/authorisation/IssuePermissionTest.java, server/sonar-db-dao/src/main/java/org/sonar/db/permission/GroupPermissionDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/permission/GroupPermissionMapper.java, server/sonar-db-dao/src/main/java/org/sonar/db/permission/UserPermissionDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/permission/UserPermissionMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/permission/GroupPermissionMapper.xml, server/sonar-db-dao/src/main/resources/org/sonar/db/permission/UserPermissionMapper.xml, server/sonar-db-dao/src/test/java/org/sonar/db/permission/GroupPermissionDaoTest.java, server/sonar-db-dao/src/test/java/org/sonar/db/permission/UserPermissionDaoTest.java, server/sonar-server/src/main/java/org/sonar/server/project/ws/ProjectsWsModule.java, server/sonar-server/src/main/java/org/sonar/server/project/ws/UpdateVisibilityAction.java, server/sonar-server/src/test/java/org/sonar/server/project/ws/ProjectsWsModuleTest.java, server/sonar-server/src/test/java/org/sonar/server/project/ws/UpdateVisibilityActionTest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/project/ProjectsService.java, sonar-ws/src/main/java/org/sonarqube/ws/client/project/UpdateVisibilityRequest.java
🌊  This PR is based on #1932, which should be reviewed first.
=> SONAR-9105 add ws projects change visibility

server/sonar-web/src/main/js/app/components/nav/component/ComponentNavMenu.js, server/sonar-web/src/main/js/app/components/nav/component/__tests__/ComponentNavMenu-test.js, server/sonar-web/src/main/js/app/components/nav/component/__tests__/__snapshots__/ComponentNavMenu-test.js.snap, server/sonar-web/src/main/js/apps/component-measures/details/history/MeasureHistory.js, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigation.js, server/sonar-web/src/main/js/components/controls/GlobalMessages.js
Addressing the following issues : 
* [Enter key is catched by the button to close the global message popup](https://jira.sonarsource.com/browse/SONAR-8854)
* [Project page extension link is wrong](https://jira.sonarsource.com/browse/SONAR-8975)
* Wrong nav menu highlighted for admin extensions in organizations (related to a comment in #1982]
=> SQ 6.4 web hardening 2

server/sonar-server/src/main/java/org/sonar/server/util/AbstractStoppableExecutorService.java
=> SONAR-7511 AbstractStoppableExecutorService produce warn logs

pom.xml, sonar-application/src/main/assembly/conf/sonar.properties
Add useSSL=false to default configuration
=> SONAR-6135 Upgrade MySQL driver to 5.1.42

sonar-ws/src/main/java/org/sonarqube/ws/client/HttpConnector.java
=> SONAR-9224 HTTP data parts must have filename to allow streaming

it/it-tests/src/test/resources/organization/OrganizationQualityProfilesPageTest/should_display_changelog.html, server/sonar-server/src/main/java/org/sonar/server/organization/OrganizationCreationImpl.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevelStartup.java, server/sonar-server/src/main/java/org/sonar/server/user/ThreadLocalUserSession.java, server/sonar-server/src/test/java/org/sonar/server/organization/OrganizationCreationImplTest.java, server/sonar-server/src/test/java/org/sonar/server/organization/ws/CreateActionTest.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/DefinedQProfileInsertRule.java
rather than DefinedQProfileCreation which does too many useless operations
=> SONAR-8888 use DefinedQProfileInsert when creating an organization

server/sonar-web/src/main/js/helpers/l10n.js
* There is a bug happening when the bundle is already cached, the 304 response is not handled correctly.
* And a second problem : if the navigator is set as `en-US` we don't detect that it's the same language as `en` that is returned by the WS as the effective language. And therefore we don't use the caching capabilities.
=> SONAR-8596 Fix a bug with cached bundles

server/sonar-web/src/main/js/app/styles/boxed-group.css, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> Minor fixes

it/it-tests/src/test/java/util/ItUtils.java, server/sonar-server/src/main/java/org/sonar/server/ui/ws/ComponentAction.java, server/sonar-server/src/main/resources/org/sonar/server/ui/ws/component-example.json, server/sonar-server/src/test/resources/org/sonar/server/ui/ws/ComponentActionTest/return_component_info_when_snapshot.json, server/sonar-web/src/main/js/app/components/nav/component/ComponentNav.js, server/sonar-web/src/main/js/app/components/nav/component/ComponentNavMeta.js, server/sonar-web/src/main/js/apps/overview/components/App.js, server/sonar-web/src/main/js/apps/overview/components/__tests__/App-test.js, server/sonar-web/src/main/js/apps/overview/components/__tests__/EmptyOverview-test.js, server/sonar-web/src/main/js/apps/overview/main/CodeSmells.js, server/sonar-web/src/main/js/apps/overview/main/enhance.js
Replace "snapshotDate" by "analysisDate" in api/navigation/component
=> SONAR-8913 Not analyzed projects on projects page

server/sonar-web/src/main/js/components/issue/popups/ChangelogPopup.js, server/sonar-web/src/main/js/components/issue/popups/__tests__/__snapshots__/ChangelogPopup-test.js.snap, server/sonar-web/src/main/less/components/bubble-popup.less, server/sonar-web/src/main/less/components/issues.less
Related to : https://groups.google.com/a/sonarsource.com/d/topic/dogfood-sonarqube/hNB29-pdFak/discussion
=> Remove avatar for system events on issues changelog popup

sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/filesystem/ByteCharsetDetector.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/filesystem/CharsetValidation.java, sonar-scanner-engine/src/test/java/org/sonar/scanner/scan/filesystem/ByteCharsetDetectorTest.java, sonar-scanner-engine/src/test/java/org/sonar/scanner/scan/filesystem/CharsetValidationTest.java, sonar-scanner-engine/src/test/java/org/sonar/scanner/scan/filesystem/MetadataGeneratorTest.java, sonar-scanner-engine/src/test/resources/org/sonar/scanner/scan/filesystem/windows-1252.txt
@henryju this is the same as a previous branch, but with recommended fixes, and into `master` instead of `6.4`.
=> Detect Windows-1252

server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevelStartup.java, server/sonar-server/src/main/java/org/sonar/server/rule/CachingRuleFinder.java, server/sonar-server/src/main/java/org/sonar/server/rule/DefaultRuleFinder.java, server/sonar-server/src/main/java/org/sonar/server/rule/RegisterRules.java, server/sonar-server/src/main/java/org/sonar/server/rule/WebServerRuleFinder.java, server/sonar-server/src/main/java/org/sonar/server/rule/WebServerRuleFinderImpl.java, server/sonar-server/src/test/java/org/sonar/server/rule/CachingRuleFinderTest.java, server/sonar-server/src/test/java/org/sonar/server/rule/DefaultRuleFinderTest.java, server/sonar-server/src/test/java/org/sonar/server/rule/RegisterRulesTest.java, server/sonar-server/src/test/java/org/sonar/server/rule/WebServerRuleFinderImplTest.java
gain on my box with vanilla SQ: from 35000ms to 25ms
=> SONAR-9191 speed up loading of QualityProfiles at startup

server/sonar-ce/src/main/java/org/sonar/ce/queue/InternalCeQueueImpl.java, server/sonar-db-dao/src/main/java/org/sonar/db/component/SnapshotDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/component/SnapshotMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/component/SnapshotMapper.xml, server/sonar-db-dao/src/test/java/org/sonar/db/component/SnapshotDaoTest.java, server/sonar-server/src/main/java/org/sonar/server/issue/index/IssueIndex.java, server/sonar-server/src/main/java/org/sonar/server/issue/index/ProjectStatistics.java, server/sonar-server/src/test/java/org/sonar/server/ce/ws/ActivityActionTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/index/IssueIndexProjectStatisticsTest.java, sonar-core/src/main/java/org/sonar/core/platform/PluginLoader.java
=> MMF-966 Developer notifications in SonarLint for IntelliJ

server/sonar-web/src/main/js/apps/organizations/components/OrganizationPage.js, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigation.js, server/sonar-web/src/main/js/apps/organizations/navigation/__tests__/OrganizationNavigation-test.js, server/sonar-web/src/main/js/apps/organizations/navigation/__tests__/__snapshots__/OrganizationNavigation-test.js.snap, server/sonar-web/src/main/js/apps/quality-gates/components/QualityGatesApp.js, tests/src/test/java/org/sonarqube/pageobjects/ProjectDashboardPage.java, tests/src/test/java/org/sonarqube/pageobjects/QualityGatePage.java, tests/src/test/java/org/sonarqube/tests/OrganizationTester.java, tests/src/test/java/org/sonarqube/tests/qualityGate/OrganizationQualityGateUiTest.java, tests/src/test/java/org/sonarqube/tests/qualityGate/QualityGateUiTest.java
=> Apply feedbacks

server/sonar-server/src/main/java/org/sonar/server/projectanalysis/ws/CreateEventAction.java, server/sonar-server/src/main/java/org/sonar/server/projectanalysis/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/ui/ws/ComponentAction.java, server/sonar-server/src/test/java/org/sonar/server/projectanalysis/ws/CreateEventActionTest.java, server/sonar-server/src/test/java/org/sonar/server/projectanalysis/ws/SearchActionTest.java, server/sonar-server/src/test/java/org/sonar/server/ui/PageRepositoryTest.java, server/sonar-server/src/test/java/org/sonar/server/ui/ws/ComponentActionTest.java
=> App in project analyses and extensions

.travis/setup_ramdisk.sh, travis.sh
* BUILD-478 Revert "Remove usage of ramdisk in travis"
This reverts commit 0abed2e4d284a393c914cff334c55b3d9c88553f.
* BUILD-478 Set TRAVIS_BUILD_DIR in ramdisk
=> enable ramdisk (#2271)

server/sonar-web/src/main/js/apps/component-measures/components/MeasureContent.js, server/sonar-web/src/main/js/apps/component-measures/components/MeasureOverview.js, server/sonar-web/src/main/js/apps/component-measures/drilldown/BubbleChart.js, server/sonar-web/src/main/js/apps/component-measures/drilldown/MeasureCell.js, server/sonar-web/src/main/js/apps/component-measures/drilldown/TreeMapView.js, server/sonar-web/src/main/js/apps/component-measures/utils.js, server/sonar-web/src/main/js/apps/projectActivity/components/Event.js, server/sonar-web/src/main/js/apps/projectActivity/components/ProjectActivityAppContainer.js, server/sonar-web/src/main/js/apps/projectActivity/components/ProjectActivityGraphs.js, server/sonar-web/src/main/js/apps/projectActivity/utils.js, server/sonar-web/src/main/js/components/charts/TreeMapRect.js, server/sonar-web/src/main/js/components/common/MultiSelect.js, server/sonar-web/src/main/js/components/issue/components/IssueCommentLine.js, server/sonar-web/src/main/js/components/issue/components/__tests__/__snapshots__/IssueCommentLine-test.js.snap, server/sonar-web/src/main/js/components/issue/popups/SetAssigneePopup.js, server/sonar-web/src/main/js/helpers/urls.js, server/sonar-web/src/main/js/store/organizations/duck.js, server/sonar-web/src/main/js/store/rootActions.js, server/sonar-web/src/main/less/components/issues.less
=> Hardening 1

server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/component/BranchLoader.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/component/BranchLoaderTest.java
=> Fix handling of legacy branches

sonar-core/src/main/java/org/sonar/core/config/CorePropertyDefinitions.java
Hey.
This PR fixes a minor spelling error and generalises punctuation use in the General Settings view.
=> Fixed a spelling error and generalized punctiation for general settings.

server/sonar-process/src/main/java/org/sonar/process/Props.java, server/sonar-process/src/test/java/org/sonar/process/PropsTest.java, server/sonar-process/src/test/java/org/sonar/process/jmvoptions/JvmOptionsTest.java, server/sonar-server/src/main/java/org/sonar/ce/settings/ProjectSettings.java, server/sonar-server/src/main/java/org/sonar/server/setting/ThreadLocalSettings.java, sonar-plugin-api/src/main/java/org/sonar/api/config/PropertyDefinitions.java, sonar-plugin-api/src/main/java/org/sonar/api/config/Settings.java, sonar-plugin-api/src/main/java/org/sonar/api/config/internal/MapSettings.java, sonar-plugin-api/src/test/java/org/sonar/api/config/ConfigurationTest.java, sonar-plugin-api/src/test/java/org/sonar/api/config/PropertyDefinitionsTest.java, sonar-plugin-api/src/test/java/org/sonar/api/config/internal/MapSettingsTest.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/GlobalConfiguration.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/MutableGlobalSettings.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/config/DefaultConfiguration.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/MutableModuleSettings.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/MutableProjectSettings.java
=> SONAR-9283 Settings, Configuration and Props trim values at insert

server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/container/ProjectAnalysisTaskContainerPopulator.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/webhook/WebhookPayloadFactory.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/webhook/WebhookPayloadFactoryImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/webhook/WebhookPostTask.java, server/sonar-server/src/main/java/org/sonar/server/platform/platformlevel/PlatformLevel4.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebHooks.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebHooksImpl.java, server/sonar-server/src/main/java/org/sonar/server/webhook/Webhook.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookCaller.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookCallerImpl.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookDelivery.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookDeliveryStorage.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookModule.java, server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookPayload.java, server/sonar-server/src/main/java/org/sonar/server/webhook/package-info.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/webhook/WebhookPayloadFactoryImplTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/webhook/WebhookPostTaskTest.java, server/sonar-server/src/test/java/org/sonar/server/webhook/TestWebhookCaller.java, server/sonar-server/src/test/java/org/sonar/server/webhook/TestWebhookPayloadFactory.java, server/sonar-server/src/test/java/org/sonar/server/webhook/WebHooksImplTest.java, server/sonar-server/src/test/java/org/sonar/server/webhook/WebhookCallerImplTest.java, server/sonar-server/src/test/java/org/sonar/server/webhook/WebhookDeliveryStorageTest.java, server/sonar-server/src/test/java/org/sonar/server/webhook/WebhookDeliveryTest.java, server/sonar-server/src/test/java/org/sonar/server/webhook/WebhookModuleTest.java, sonar-plugin-api/src/main/java/org/sonar/api/ce/posttask/PostProjectAnalysisTaskTester.java
as well as we use it in CE report processing
=> SONAR-9871 move webhook code to use it in web

server/sonar-web/src/main/js/apps/users/form-view.js, server/sonar-web/src/main/js/apps/users/templates/users-form.hbs
Your favorite backbone+handlebars stack 😉
=> SONAR-9195 Ease removing of SCM accounts

server/sonar-web/src/main/js/apps/coding-rules/controller.js, server/sonar-web/src/main/js/apps/coding-rules/rule/rule-profiles-view.js, server/sonar-web/src/main/js/apps/coding-rules/templates/coding-rules-workspace-list-item.hbs, server/sonar-web/src/main/js/apps/coding-rules/templates/rule/coding-rules-profile-activation.hbs, server/sonar-web/src/main/js/apps/coding-rules/templates/rule/coding-rules-rule-profile.hbs, server/sonar-web/src/main/js/apps/coding-rules/workspace-list-item-view.js, server/sonar-web/src/main/js/apps/projectActivity/components/__tests__/__snapshots__/ProjectActivityDateInput-test.js.snap, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/__snapshots__/Search-test.tsx.snap, server/sonar-web/src/main/js/components/SourceViewer/views/templates/_source-viewer-measures-duplications.hbs, server/sonar-web/src/main/js/components/controls/DateInput.tsx, server/sonar-web/src/main/less/components/source.less, server/sonar-web/src/main/less/variables.less
To test SONAR-8371 you can search for java rule with key `S1820 `
=> Stas Hardening Oct 9

server/sonar-main/src/main/java/org/sonar/application/SchedulerImpl.java, server/sonar-main/src/main/java/org/sonar/application/cluster/health/HealthStateSharingImpl.java, server/sonar-main/src/main/java/org/sonar/application/config/FileSystemSettings.java, server/sonar-main/src/main/java/org/sonar/application/config/JdbcSettings.java, server/sonar-main/src/main/java/org/sonar/application/process/ProcessLauncherImpl.java, server/sonar-main/src/main/java/org/sonar/application/process/SQProcess.java, server/sonar-process/src/main/java/org/sonar/process/Jmx.java, server/sonar-process/src/main/java/org/sonar/process/ProcessEntryPoint.java, server/sonar-process/src/main/java/org/sonar/process/StopperThread.java, server/sonar-process/src/main/java/org/sonar/process/cluster/health/SharedHealthStateImpl.java, sonar-plugin-api/src/main/java/org/sonar/api/utils/TimeProfiler.java, sonar-plugin-api/src/test/java/org/sonar/api/utils/TimeProfilerTest.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/phases/CoverageExclusions.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/DefaultSensorStorage.java
=> External contribution: slf4j related fixes

server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/component/BranchPersister.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/component/BranchPersisterImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/container/ProjectAnalysisTaskContainerPopulator.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/component/BranchPersisterImplTest.java
This will allow privileged plugin as GOV to do nothing on branch
=> SONAR-9991 Set BranchPersister as Inteface

server/sonar-server/src/main/java/org/sonar/server/webhook/WebhookPayloadFactoryImpl.java, server/sonar-server/src/test/java/org/sonar/server/webhook/WebhookPayloadFactoryImplTest.java, tests/src/test/java/org/sonarqube/tests/webhook/WebhooksTest.java
URLs for branches are now checked in branch IT : https://github.com/SonarSource/sonar-branch/pull/48
=> SONAR-9869 Fix project urls in webhook payload

server/sonar-db-dao/src/main/java/org/sonar/db/component/SnapshotDto.java, server/sonar-db-dao/src/test/java/org/sonar/db/component/SnapshotDtoTest.java, server/sonar-server/src/main/java/org/sonar/server/projectanalysis/ws/UpdateEventAction.java, server/sonar-server/src/test/java/org/sonar/server/projectanalysis/ws/UpdateEventActionTest.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/ProjectReactorValidator.java, sonar-scanner-engine/src/test/java/org/sonar/scanner/scan/ProjectReactorValidatorTest.java
=> SONAR-7992 Restrict length of version names

server/sonar-web/src/main/js/app/styles/init/icons.css
=> fix fonts path

server/sonar-db-migration/src/main/java/org/sonar/server/platform/db/migration/engine/MigrationContainerImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/container/TaskContainer.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/container/TaskContainerImpl.java, server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/taskprocessor/ReportTaskProcessor.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/container/TaskContainerImplTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/container/ProjectAnalysisTaskContainerPopulatorTest.java, sonar-core/src/main/java/org/sonar/core/platform/ComponentContainer.java, sonar-core/src/main/java/org/sonar/core/platform/StopSafeReflectionLifecycleStrategy.java, sonar-core/src/test/java/org/sonar/core/platform/ComponentContainerTest.java, sonar-scanner-engine/src/main/java/org/sonar/batch/bootstrapper/Batch.java, tests/plugins/fake-governance-plugin/src/main/java/FakeGovernancePlugin.java, tests/plugins/fake-governance-plugin/src/main/java/ce/BombConfig.java, tests/plugins/fake-governance-plugin/src/main/java/ce/ComponentBombReportAnalysisComponentProvider.java, tests/plugins/fake-governance-plugin/src/main/java/ce/IseTaskProcessor.java, tests/plugins/fake-governance-plugin/src/main/java/ce/OOMGenerator.java, tests/plugins/fake-governance-plugin/src/main/java/ce/OkTaskProcessor.java, tests/plugins/fake-governance-plugin/src/main/java/ce/OomTaskProcessor.java, tests/plugins/fake-governance-plugin/src/main/java/ce/ws/BombActivatorAction.java, tests/plugins/fake-governance-plugin/src/main/java/ce/ws/FakeGoVWsAction.java, tests/plugins/fake-governance-plugin/src/main/java/ce/ws/FakeGovWs.java, tests/plugins/fake-governance-plugin/src/main/java/ce/ws/SubmitAction.java, tests/src/test/java/org/sonarqube/tests/ce/CeWorkersTest.java
and ensures all stoppable and/or disposable components in the container have their stop and/or dispose methods called
=> SONAR-9973 ComponentContainer#stopComponent now never fail

server/sonar-server/src/main/java/org/sonar/server/component/ws/SearchProjectsAction.java, server/sonar-server/src/main/java/org/sonar/server/component/ws/SuggestionsAction.java, server/sonar-server/src/main/java/org/sonar/server/component/ws/TreeAction.java, server/sonar-server/src/main/java/org/sonar/server/measure/ws/ComponentTreeAction.java, server/sonar-server/src/main/java/org/sonar/server/organization/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/GroupsAction.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/UsersAction.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/TemplateGroupsAction.java, server/sonar-server/src/main/java/org/sonar/server/permission/ws/template/TemplateUsersAction.java, server/sonar-server/src/main/java/org/sonar/server/rule/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/user/ws/SearchAction.java, server/sonar-server/src/main/java/org/sonar/server/ws/ws/ListAction.java, server/sonar-server/src/main/resources/org/sonar/server/ws/ws/list-example.json, server/sonar-server/src/test/java/org/sonar/server/component/ws/TreeActionTest.java, server/sonar-server/src/test/java/org/sonar/server/measure/ws/ComponentTreeActionTest.java, server/sonar-server/src/test/java/org/sonar/server/permission/ws/UsersActionTest.java, server/sonar-server/src/test/java/org/sonar/server/ws/ws/WebServicesWsTest.java, server/sonar-server/src/test/resources/org/sonar/server/ws/ws/WebServicesWsTest/list_including_internals.json, sonar-plugin-api/src/main/java/org/sonar/api/server/ws/WebService.java, sonar-plugin-api/src/main/java/org/sonar/api/server/ws/internal/ValidatingRequest.java, sonar-plugin-api/src/test/java/org/sonar/api/server/ws/WebServiceTest.java
SONAR-10046 Check minimum length of search parameters in WS
=> SONAR-10046 Add new constraints on ws api

server/sonar-server/src/main/java/org/sonar/server/ce/ws/ComponentAction.java, server/sonar-server/src/test/java/org/sonar/server/ce/ws/ComponentActionTest.java, sonar-ws-generated/src/main/java/org/sonarqube/ws/client/ce/CeService.java, sonar-ws-generated/src/main/protobuf/ws-ce.proto
The new name "ComponentResponse" will allow to autogenerate sonar-ws for this webservice
=> Rename protobuf response of api/ce/component

server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/UpdateConditionAction.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/ws/UpdateConditionActionTest.java
=> SONAR-10134 Add organization parameter in some actions

server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/qualitygate/QualityGateMapper.xml, server/sonar-db-dao/src/test/java/org/sonar/db/qualitygate/QualityGateDaoTest.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/QualityGateFinder.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/CreateConditionAction.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/DeleteConditionAction.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/QualityGatesWsSupport.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/ws/UpdateConditionAction.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/ws/CreateConditionActionTest.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/ws/DeleteConditionActionTest.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/ws/UpdateConditionActionTest.java
=> SONAR-10134 Add organization parameter in conditions ws

server/sonar-web/src/main/js/apps/portfolio/components/App.tsx, server/sonar-web/src/main/js/apps/portfolio/components/__tests__/App-test.tsx, server/sonar-web/src/main/js/apps/projectsManagement/App.tsx, server/sonar-web/src/main/js/apps/projectsManagement/AppContainer.tsx, server/sonar-web/src/main/js/apps/projectsManagement/ProjectRow.tsx, server/sonar-web/src/main/js/apps/projectsManagement/ProjectRowActions.tsx, server/sonar-web/src/main/js/apps/projectsManagement/Projects.tsx, server/sonar-web/src/main/js/apps/projectsManagement/RestoreAccessModal.tsx, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/App-test.tsx, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/ProjectRow-test.tsx, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/ProjectRowActions-test.tsx, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/Projects-test.tsx, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/__snapshots__/ProjectRow-test.tsx.snap, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/__snapshots__/ProjectRowActions-test.tsx.snap, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/__snapshots__/Projects-test.tsx.snap, server/sonar-web/src/main/js/apps/quality-profiles/home/CreateProfileForm.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> 6.7 bug fixes

server/sonar-web/src/main/js/app/components/nav/component/ComponentNavHeader.tsx, server/sonar-web/src/main/js/app/components/nav/component/__tests__/__snapshots__/ComponentNavHeader-test.tsx.snap, server/sonar-web/src/main/js/apps/projects/components/PageHeader.tsx
Fragments actually allowed to reduce code complexity!
=> reduce code complexity

server/sonar-web/src/main/js/apps/coding-rules/rule/rule-issues-view.js, server/sonar-web/src/main/js/apps/component-measures/drilldown/ComponentCell.js, server/sonar-web/src/main/js/components/SourceViewer/SourceViewerHeader.js, server/sonar-web/src/main/js/helpers/__tests__/urls-test.ts, server/sonar-web/src/main/js/helpers/urls.ts
Fixes : https://jira.sonarsource.com/browse/SONAR-10177
=> SONAR-10177 Dont rely on router Link in the source code viewer header

server/sonar-db-dao/src/main/java/org/sonar/db/user/UserDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/user/UserMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/user/UserMapper.xml, server/sonar-db-dao/src/test/java/org/sonar/db/user/UserDaoTest.java, server/sonar-server/src/main/java/org/sonar/server/component/ComponentCleanerService.java, server/sonar-server/src/main/java/org/sonar/server/organization/ws/DeleteAction.java, server/sonar-server/src/main/java/org/sonar/server/user/ws/CurrentAction.java, server/sonar-server/src/main/java/org/sonar/server/user/ws/SetHomepageAction.java, server/sonar-server/src/main/resources/org/sonar/server/user/ws/current-example.json, server/sonar-server/src/test/java/org/sonar/server/organization/ws/DeleteActionTest.java, server/sonar-server/src/test/java/org/sonar/server/project/ws/DeleteActionTest.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/CurrentActionTest.java, server/sonar-server/src/test/java/org/sonar/server/user/ws/SetHomepageActionTest.java, sonar-ws/src/main/protobuf/ws-users.proto
please disregard first commit it's covered by previous pr, but until she is merged i have no way of segregating.
=> feature/guillaume/sonar 10183/adding persistence

server/sonar-server/src/main/java/org/sonar/server/ws/WebServiceEngine.java, server/sonar-server/src/main/java/org/sonar/server/ws/WsUtils.java, server/sonar-server/src/test/java/org/sonar/server/ws/TestRequest.java, server/sonar-server/src/test/java/org/sonar/server/ws/WebServiceEngineTest.java, sonar-plugin-api/src/main/java/org/sonar/api/server/ws/Response.java, sonar-plugin-api/src/main/java/org/sonar/api/server/ws/WebService.java
* in case of response partially streamed a debug message is logged
* protobuf messages are streamed
=> SONAR-10154 Delegate resource management of JsonWriter's Writer to the caller

server/sonar-web/src/main/js/apps/coding-rules/bulk-change-modal-view.js
@gregaubert sorry for the huge PR 😄
=> SONAR-10236 Cannot bulk activate/deactivate rules when using a web context

server/sonar-web/src/main/js/apps/issues/components/BulkChangeModal.js, server/sonar-web/src/main/js/apps/issues/utils.js, server/sonar-web/src/main/js/components/controls/SearchSelect.tsx, server/sonar-web/src/main/js/components/controls/__tests__/SearchSelect-test.tsx, server/sonar-web/src/main/js/components/controls/__tests__/__snapshots__/SearchSelect-test.tsx.snap, server/sonar-web/src/main/js/components/facet/__tests__/__snapshots__/FacetFooter-test.js.snap
Fixes the bug related to this issue : https://jira.sonarsource.com/browse/SONAR-10298
I did not reference it in the commit message because the ticket is gonna be dropped once it's merged on branch-7.0
=> Add back missing action to bulk unassign issues

plugins/sonar-xoo-plugin/src/test/java/org/sonar/xoo/XooPluginTest.java, server/sonar-server/src/main/java/org/sonar/server/plugins/ServerExtensionInstaller.java, sonar-plugin-api/src/main/java/org/sonar/api/Plugin.java, sonar-plugin-api/src/main/java/org/sonar/api/internal/PluginContextImpl.java, sonar-plugin-api/src/test/java/org/sonar/api/PluginTest.java, sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/ExtensionInstaller.java, sonar-scanner-engine/src/test/java/org/sonar/scanner/bootstrap/ExtensionInstallerTest.java
That allows plugins to check configuration when providing the list
of extensions.
=> Add Java API Plugin.Context#getBootConfiguration()

server/sonar-web/src/main/js/app/components/Landing.tsx, server/sonar-web/src/main/js/app/components/nav/component/ComponentNavMeta.tsx, server/sonar-web/src/main/js/app/types.ts, server/sonar-web/src/main/js/apps/issues/components/App.js, server/sonar-web/src/main/js/apps/issues/components/PageActions.js, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigationMeta.tsx, server/sonar-web/src/main/js/apps/organizations/navigation/__tests__/__snapshots__/OrganizationNavigationMeta-test.tsx.snap, server/sonar-web/src/main/js/apps/projects/components/PageHeader.tsx, server/sonar-web/src/main/js/apps/projects/components/__tests__/__snapshots__/PageHeader-test.tsx.snap, server/sonar-web/src/main/js/components/controls/HomePageSelect.tsx, server/sonar-web/src/main/js/components/controls/__tests__/HomePageSelect-test.tsx, server/sonar-web/src/main/js/components/controls/__tests__/__snapshots__/HomePageSelect-test.tsx.snap, server/sonar-web/src/main/js/helpers/urls.ts
There changes have been done:
- add new options for home page
- add branch support
- stricter home page typing
🚧 🚧 WS is not yet ready! 🚧 🚧
=> SONAR-10423 display home page selector

server/sonar-server/src/main/java/org/sonar/server/qualitygate/changeevent/QGChangeEventListener.java, server/sonar-server/src/main/java/org/sonar/server/qualitygate/changeevent/QGChangeEventListenersImpl.java, server/sonar-server/src/test/java/org/sonar/server/qualitygate/changeevent/QGChangeEventListenersImplTest.java
Used for sonar-core-plugins QA
=> BRANCH-45 Expose issue resolution for PR decoration

server/sonar-web/src/main/js/app/components/nav/component/ComponentNavMenu.tsx, server/sonar-web/src/main/js/app/components/nav/component/__tests__/__snapshots__/ComponentNavMenu-test.tsx.snap, server/sonar-web/src/main/js/apps/issues/components/App.js, server/sonar-web/src/main/js/apps/issues/conciseIssuesList/ConciseIssuesListHeader.js
I took the decision to simply remove the back button instead of loading the entire list of issue, at it seems to me to be the expected behavior on a permalink.
Feel free to ping me if this needs more discussion.
=> SONAR-10379 Improve issue permalink UX

cix.sh, run-integration-tests.sh, run-perf-tests.sh, run-upgrade-tests.sh, tests/build.gradle
Logs only skipped and failing tests (with full stack trace)
Remove any other output
=> Improve logging for ITs

server/sonar-server/src/main/java/org/sonar/server/qualityprofile/RuleActivator.java, server/sonar-server/src/test/java/org/sonar/server/qualityprofile/BuiltInQProfileUpdateImplTest.java
Please ensure your pull request adheres to the following guidelines:
=> SONAR-10473 Small refactoring and add test to check QP always up-to-date

server/sonar-web/src/main/js/apps/overview/components/App.js, server/sonar-web/src/main/js/apps/overview/components/EmptyOverview.js, server/sonar-web/src/main/js/apps/overview/components/__tests__/EmptyOverview-test.js, server/sonar-web/src/main/js/apps/overview/components/__tests__/__snapshots__/EmptyOverview-test.js.snap, server/sonar-web/src/main/less/init/type.less, sonar-core/src/main/resources/org/sonar/l10n/core.properties
⚠️ DO NOT FORGET TO MERGE TO MASTER! ⚠️
@pascal-mugnier-sonarsource I can show how to test on Monday.
=> SONAR-10221 Change message when project main branch is not analyzed

server/sonar-server/src/main/java/org/sonar/server/issue/IssueQuery.java, server/sonar-server/src/main/java/org/sonar/server/issue/IssueQueryFactory.java, server/sonar-server/src/main/java/org/sonar/server/issue/index/IssueIndex.java, server/sonar-server/src/test/java/org/sonar/server/issue/IssueQueryFactoryTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/IssueQueryTest.java, server/sonar-server/src/test/java/org/sonar/server/issue/index/IssueIndexTest.java, server/sonar-web/src/main/js/components/SourceViewer/SourceViewerBase.js
Please ensure your pull request adheres to the following guidelines:
=> SONAR-10451 Incorrect filtering on "Leak Period" issues in the Issues page

server/sonar-web/src/main/js/app/components/nav/component/ComponentNavBgTaskNotif.tsx, server/sonar-web/src/main/js/app/components/nav/component/__tests__/ComponentNavBgTaskNotif-test.tsx, server/sonar-web/src/main/js/app/components/nav/component/__tests__/__snapshots__/ComponentNavBgTaskNotif-test.tsx.snap, server/sonar-web/src/main/js/components/issue/components/IssueAssign.js, server/sonar-web/src/main/js/components/issue/components/IssueCommentLine.js, server/sonar-web/src/main/js/components/issue/popups/SimilarIssuesPopup.js, server/sonar-web/src/main/js/components/ui/Avatar.js, server/sonar-web/src/main/js/components/ui/__tests__/Avatar-test.js, server/sonar-web/src/main/js/components/ui/__tests__/__snapshots__/Avatar-test.js.snap, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> Hardening 6.7

server/sonar-ce/src/main/java/org/sonar/ce/queue/PurgeCeActivities.java, server/sonar-ce/src/test/java/org/sonar/ce/queue/PurgeCeActivitiesTest.java, server/sonar-db-dao/src/main/java/org/sonar/db/ce/CeScannerContextDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/ce/CeScannerContextMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/ce/CeScannerContextMapper.xml, server/sonar-db-dao/src/test/java/org/sonar/db/ce/CeScannerContextDaoTest.java
=> SONAR-9218 purge ce_scanner_context older than 28 days at startup

server/sonar-server/src/main/java/org/sonar/server/computation/task/projectanalysis/step/UnitTestMeasuresStep.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/formula/ReportFormulaExecutorComponentVisitorTest.java, server/sonar-server/src/test/java/org/sonar/server/computation/task/projectanalysis/step/ReportUnitTestMeasuresStepTest.java, tests/plugins/pom.xml, tests/plugins/save-measure-on-module-plugin/pom.xml, tests/plugins/save-measure-on-module-plugin/src/main/java/org/sonar/measure/ModuleMeasureSensor.java, tests/plugins/save-measure-on-module-plugin/src/main/java/org/sonar/measure/SaveMeasureOnModulePlugin.java, tests/projects/analysis/xoo-module-b-without-source/module_a/sonar-project.properties, tests/projects/analysis/xoo-module-b-without-source/module_a/src/main/xoo/com/sonar/it/samples/modules/a1/HelloA1.xoo, tests/projects/analysis/xoo-module-b-without-source/module_a/src/main/xoo/com/sonar/it/samples/modules/a1/HelloA1.xoo.measures, tests/projects/analysis/xoo-module-b-without-source/module_b/sonar-project.properties, tests/projects/analysis/xoo-module-b-without-source/sonar-project.properties, tests/src/test/java/org/sonarqube/tests/Category3Suite.java, tests/src/test/java/org/sonarqube/tests/analysis/ProjectMeasureTest.java
This PR is a backport of https://github.com/SonarSource/sonar-enterprise/pull/157 for SonarQube 6.7
=> SONAR-10852 Fix project analysis without src but with test measures
